name: 'Determine Affected Packages'
description: 'Identifies packages affected by changes in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  changed_files:
    description: 'JSON array of changed files'
    required: true
  apps_configuration:
    description: 'JSON object containing app configurations'
    required: true

outputs:
  affected_apps:
    description: 'JSON array of affected app names'

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Install dependencies
    shell: bash
    run: npm install @actions/github @actions/core

  - name: Determine affected packages
    id: determine-affected
    shell: node
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      CHANGED_FILES: ${{ inputs.changed_files }}
      APPS_CONFIG: ${{ inputs.apps_configuration }}
    run: |
      const github = require('@actions/github');
      const core = require('@actions/core');

      async function determineAffectedPackages() {
        try {
          const changedFiles = JSON.parse(process.env.CHANGED_FILES);
          const appsConfig = JSON.parse(process.env.APPS_CONFIG);

          const affectedApps = new Set();

          changedFiles.forEach(file => {
            appsConfig.forEach(app => {
              if (file.startsWith(app.directory)) {
                affectedApps.add(app.name);
              }
            });
          });

          const affectedAppsArray = Array.from(affectedApps);
          core.setOutput('affected_apps', JSON.stringify(affectedAppsArray));
          console.log('Affected apps:', affectedAppsArray);
        } catch (error) {
          core.setFailed(`Error determining affected packages: ${error.message}`);
        }
      }

      determineAffectedPackages();

  - name: Error handling
    if: failure()
    shell: bash
    run: |
      echo "An error occurred while determining affected packages."
      echo "affected_apps=[]" >> $GITHUB_OUTPUT
