name: 'Update Security Policy'
description: 'Updates the repository security policy based on security analysis results'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  security-report:
    description: 'JSON string containing the security analysis report'
    required: true
  ai-analysis:
    description: 'AI-generated analysis of the security report'
    required: true

outputs:
  policy-updated:
    description: 'Boolean indicating whether the policy was updated'
  update-summary:
    description: 'Summary of updates made to the security policy'

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Parse security report and AI analysis
    id: parse-inputs
    shell: bash -l {0}
    run: |
      echo "${{ inputs.security-report }}" > security_report.json
      echo "${{ inputs.ai-analysis }}" > ai_analysis.txt

  - name: Update security policy
    id: update-policy
    shell: bash -l {0}
    run: |
      POLICY_PATH='.github/SECURITY.md'
      POLICY_UPDATED=false
      UPDATE_SUMMARY=""

      # Update supported versions
      SUPPORTED_VERSIONS=$(jq -r '.supportedVersions | join("\n- ")' security_report.json)
      if [ ! -z "$SUPPORTED_VERSIONS" ]; then
        sed -i '/## Supported Versions/,/##/c\## Supported Versions\n\nThe following versions are currently supported with security updates:\n\n- '"$SUPPORTED_VERSIONS"'\n\n##' $POLICY_PATH
        POLICY_UPDATED=true
        UPDATE_SUMMARY="Updated supported versions"
      fi

      # Update reporting process based on AI analysis
      REPORTING_PROCESS=$(sed -n '/Reporting Process:/,/^$/p' ai_analysis.txt)
      if [ ! -z "$REPORTING_PROCESS" ]; then
        sed -i '/## Reporting a Vulnerability/,/##/c\## Reporting a Vulnerability\n\n'"$REPORTING_PROCESS"'\n\n##' $POLICY_PATH
        POLICY_UPDATED=true
        UPDATE_SUMMARY="$UPDATE_SUMMARY, Updated vulnerability reporting process"
      fi

      echo "policy-updated=$POLICY_UPDATED" >> $GITHUB_OUTPUT
      echo "update-summary=$UPDATE_SUMMARY" >> $GITHUB_OUTPUT

  - name: Commit changes
    if: steps.update-policy.outputs.policy-updated == 'true'
    shell: bash -l {0}
    run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git add .github/SECURITY.md
      git commit -m "Update security policy based on latest analysis"
      git push
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}

  - name: Error handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "An error occurred while updating the security policy."
      echo "policy-updated=false" >> $GITHUB_OUTPUT
      echo "update-summary=Failed to update security policy due to an error" >> $GITHUB_OUTPUT
