name: 'Create Wiki Page'
description: 'Creates a new wiki page in the repository using GitHub API'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  page-name:
    description: 'Name of the wiki page to create'
    required: true
  page-content:
    description: 'Content of the wiki page'
    required: true

outputs:
  page-url:
    description: 'URL of the created wiki page'

runs:
  using: 'composite'
  steps:
  - name: Create Wiki Page
    id: create-wiki-page
    uses: fjogeleit/http-request-action@v1
    with:
      url: https://api.github.com/repos/${{ github.repository }}/wiki/${{ inputs.page-name }}
      method: 'PUT'
      bearerToken: ${{ inputs.github-token }}
      customHeaders: '{"Accept": "application/vnd.github.v3+json"}'
      data: >
        {
          "message": "Create ${{ inputs.page-name }} wiki page",
          "content": "${{ inputs.page-content }}"
        }

  - name: Process response
    shell: bash
    run: |
      response='${{ steps.create-wiki-page.outputs.response }}'
      html_url=$(echo "$response" | jq -r '.html_url')
      if [[ "$html_url" != "null" ]]; then
        echo "Wiki page created successfully"
        echo "page-url=$html_url" >> $GITHUB_OUTPUT
      else
        echo "Failed to create wiki page"
        echo "Error: $(echo "$response" | jq -r '.message')"
        exit 1
      fi
