name: 'Create or Update Branch'
description: 'Creates a new branch or updates an existing one'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  branch-name:
    description: 'Name of the branch to create or update'
    required: true
  base-branch:
    description: 'Name of the base branch'
    required: true
  commit-changes:
    description: 'Changes to commit if updating the branch'
    required: false

outputs:
  branch-url:
    description: 'URL of the created or updated branch'
  operation-status:
    description: 'Status of the branch operation (created/updated/unchanged)'

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Debug Input Values
    shell: bash
    run: |
      echo "Debug: Input Values"
      echo "github-token: ${{ inputs.github-token }}"
      echo "branch-name: ${{ inputs.branch-name }}"
      echo "base-branch: ${{ inputs.base-branch }}"
      echo "commit-changes: ${{ inputs.commit-changes }}"

  - name: Create or update branch
    id: branch-operation
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      BRANCH_NAME: ${{ inputs.branch-name }}
      BASE_BRANCH: ${{ inputs.base-branch }}
      COMMIT_CHANGES: ${{ inputs.commit-changes }}
    run: |
      set -e

      echo "Debug: Starting branch operation"

      # Check if branch exists
      if git ls-remote --exit-code --heads origin $BRANCH_NAME > /dev/null 2>&1; then
        BRANCH_EXISTS=true
        echo "Debug: Branch $BRANCH_NAME exists"
      else
        BRANCH_EXISTS=false
        echo "Debug: Branch $BRANCH_NAME does not exist"
      fi

      if [ "$BRANCH_EXISTS" = false ]; then
        # Create new branch
        echo "Debug: Creating new branch $BRANCH_NAME"
        git checkout -b $BRANCH_NAME origin/$BASE_BRANCH
        git push origin $BRANCH_NAME
        echo "operation-status=created" >> $GITHUB_OUTPUT
      else
        # Update existing branch
        echo "Debug: Updating existing branch $BRANCH_NAME"
        git checkout $BRANCH_NAME
        git reset --hard origin/$BASE_BRANCH
        git push --force origin $BRANCH_NAME
        echo "operation-status=updated" >> $GITHUB_OUTPUT
      fi

      # Apply commit changes if provided
      if [ -n "$COMMIT_CHANGES" ]; then
        echo "Debug: Applying commit changes"
        echo "$COMMIT_CHANGES" > changes.patch
        git apply changes.patch
        git add .
        git commit -m "Apply changes from action"
        git push origin $BRANCH_NAME
      else
        echo "Debug: No commit changes provided"
      fi

      # Generate branch URL
      REPO_URL=$(git config --get remote.origin.url | sed 's/\.git$//')
      BRANCH_URL="${REPO_URL}/tree/${BRANCH_NAME}"
      echo "branch-url=$BRANCH_URL" >> $GITHUB_OUTPUT
      echo "Debug: Branch URL: $BRANCH_URL"

  - name: Error handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "Debug: An error occurred during branch creation/update"
      echo "operation-status=failed" >> $GITHUB_OUTPUT

  - name: Debug Output Values
    shell: bash
    run: |
      echo "Debug: Output Values"
      echo "branch-url: ${{ steps.branch-operation.outputs.branch-url }}"
      echo "operation-status: ${{ steps.branch-operation.outputs.operation-status }}"
