# Repository Configuration
repository: !include repository.config.yml

# Package Management
packages: !include packages.config.yml

# Pull Request Management
pr_management: !include pr_management.config.yml

# Issue Management
issue_management: !include issue-management.config.yml

# Release Management
release_management: !include release-management.config.yml

# Security and Dependency Management
security_dependency_management: !include security-dependency-management.config.yml

# Automated Testing
automated_testing: !include automated-testing.config.yml

# Metrics Generation
metrics_generation: !include metrics-generation.config.yml

# Cron Jobs
cron_jobs: !include cron-jobs.config.yml

# Plugins
plugins: !include plugins.config.yml
