# Anchor definitions
repository_config: &repository_config
  file: ./configs/repository.config.yml

packages_config: &packages_config
  file: ./configs/packages.config.yml

pr_management_config: &pr_management_config
  file: ./configs/pr_management.config.yml

issue_management_config: &issue_management_config
  file: ./configs/issue-management.config.yml

release_management_config: &release_management_config
  file: ./configs/release-management.config.yml

security_dependency_management_config: &security_dependency_management_config
  file: ./configs/security-dependency-management.config.yml

automated_testing_config: &automated_testing_config
  file: ./configs/automated-testing.config.yml

metrics_generation_config: &metrics_generation_config
  file: ./configs/metrics-generation.config.yml

cron_jobs_config: &cron_jobs_config
  file: ./configs/cron-jobs.config.yml

plugins_config: &plugins_config
  file: ./configs/plugins.config.yml

# Configuration sections
repository:
  !!merge <<: *repository_config

packages:
  !!merge <<: *packages_config

pr_management:
  !!merge <<: *pr_management_config

issue_management:
  !!merge <<: *issue_management_config

release_management:
  !!merge <<: *release_management_config

security_dependency_management:
  !!merge <<: *security_dependency_management_config

automated_testing:
  !!merge <<: *automated_testing_config

metrics_generation:
  !!merge <<: *metrics_generation_config

cron_jobs:
  !!merge <<: *cron_jobs_config

plugins:
  !!merge <<: *plugins_config
