# Repository Configuration
repository: !include ./configs/repository.config.yml

# Package Management
packages: !include ./configs/packages.config.yml

# Pull Request Management
pr_management: !include ./configs/pr_management.config.yml

# Issue Management
issue_management: !include ./configs/issue-management.config.yml

# Release Management
release_management: !include ./configs/release-management.config.yml

# Security and Dependency Management
security_dependency_management: !include ./configs/security-dependency-management.config.yml

# Automated Testing
automated_testing: !include ./configs/automated-testing.config.yml

# Metrics Generation
metrics_generation: !include ./configs/metrics-generation.config.yml

# Cron Jobs
cron_jobs: !include ./configs/cron-jobs.config.yml

# Plugins
plugins: !include ./configs/plugins.config.yml
