# Repository Configuration
repository:
  file: ./configs/repository.config.yml

# Package Management
packages:
  file: ./configs/packages.config.yml

# Pull Request Management
pr_management:
  file: ./configs/pr_management.config.yml

# Issue Management
issue_management:
  file: ./configs/issue-management.config.yml

# Release Management
release_management:
  file: ./configs/release-management.config.yml

# Security and Dependency Management
security_dependency_management:
  file: ./configs/security-dependency-management.config.yml

# Automated Testing
automated_testing:
  file: ./configs/automated-testing.config.yml

# Metrics Generation
metrics_generation:
  file: ./configs/metrics-generation.config.yml

# Cron Jobs
cron_jobs:
  file: ./configs/cron-jobs.config.yml

# Plugins
plugins:
  file: ./configs/plugins.config.yml
