cron_jobs:
- name: dependency_management
  schedule: "0 0 * * 1" # Weekly on Monday at 00:00 UTC
- name: security_checks
  schedule: "0 2 * * 1" # Weekly on Monday at 02:00 UTC
- name: metrics_collection
  schedule: "0 1 * * 1" # Weekly on Monday at 01:00 UTC
- name: documentation_update
  schedule: "0 2 1 * *" # Monthly on the 1st at 02:00 UTC
- name: stale_branch_cleanup
  schedule: "0 0 * * *" # Daily at 00:00 UTC
- name: issue_management
  schedule: "0 1 * * *" # Daily at 01:00 UTC
- name: performance_availability_monitoring
  schedule: "*/15 * * * *" # Every 15 minutes
