release_management:
  version_bump:
    strategy: semantic
    default_increment: patch
  changelog:
    auto_generate: true
    template: .github/templates/changelog_template.md
  affected_apps:
    detection_method: git_diff
  pre_release_checks:
  - run_tests
  - build_app
  - generate_documentation
  post_release_actions:
  - update_project_board
  - notify_slack
  release_notes:
    template: .github/templates/release_notes_template.md
    ai_generation:
      enabled: true
      prompt_template: .github/templates/release_notes_ai_prompt.md
  deployment:
    strategy: rolling
    environments:
    - staging
    - production
  approval_required:
    production: true
  rollback_strategy:
    enabled: true
    steps:
    - revert_deployment
    - notify_team
