repository:
  name: shadcn-theme-creator-for-chrome
  type: monorepo
  version_control:
    main_branches:
    - main
    - develop
    branch_prefixes:
      feature: feature/
      release: release/
      hotfix: hotfix/
    branch_protection:
      require_pull_request: true
      required_approvals: 2
      enforce_admins: true
    merge_strategy:
      develop_to_main: squash
      feature_to_develop: merge
    auto_delete_merged_branches: true
    stale_branch_threshold: 30 # days
    pr_creation_wait_time: 15 # minutes
    protected_branches:
    - main
    - develop
  setup:
    initial_branches:
    - main
    - develop
    - release
    - hotfix
    branch_protection_rules:
      main:
        required_approvals: 2
        status_checks_required: true
      develop:
        required_approvals: 1
        status_checks_required: true
    initial_labels:
    - name: bug
      color: d73a4a
    - name: enhancement
      color: a2eeef
    - name: documentation
      color: 0075ca
    - name: security
      color: d93f0b
    - name: critical
      color: b60205
    project_board:
      name: Development Workflow
      columns:
      - To Do
      - In Progress
      - Review
      - Done
    wiki_pages:
    - title: "Git Flow Process"
      content_file: .github/wiki/git_flow_process.md
    - title: "Branching Strategy"
      content_file: .github/wiki/branching_strategy.md
    - title: "Release Process"
      content_file: .github/wiki/release_process.md
    initial_workflows:
    - ci-cd.yml
    - branch-management.yml
    - issue-management.yml
    - pr-management.yml
    - security-dependency-management.yml
    - repository-setup.yml
    repository_settings:
      has_issues: true
      has_projects: true
      has_wiki: true
      delete_branch_on_merge: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: true
    dependabot_setup:
      package_ecosystems:
      - npm
      - github-actions
      schedule:
        interval: weekly
    code_owners:
      path: .github/CODEOWNERS
      default_owners:
      - "@repo-admins"
    initial_files:
    - README.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - .github/SECURITY.md
