name: 'Manage Deployment'
description: 'Handles deployment operations including deployment, verification, and rollback'

inputs:
  operation:
    description: 'Operation to perform (deploy/verify/rollback)'
    required: true
  deployment-info:
    description: 'JSON string containing deployment information'
    required: true
  environment:
    description: 'Target environment for the operation'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  operation-status:
    description: 'Status of the performed operation'
  deployment-url:
    description: 'URL of the deployed application (for deploy operation)'
  verification-result:
    description: 'Result of deployment verification (for verify operation)'
  rollback-status:
    description: 'Status of rollback operation (for rollback operation)'

runs:
  using: 'composite'
  steps:
  - name: Parse deployment information
    id: parse-info
    shell: bash
    run: |
      echo '${{ inputs.deployment-info }}' | jq -r 'to_entries | .[] | "echo \(.key)=\(.value) >> $GITHUB_OUTPUT"' | sh

  - name: Deploy application
    if: inputs.operation == 'deploy'
    uses: ./.github/actions/deploy-app
    with:
      package-name: ${{ steps.parse-info.outputs.appName }}
      artifacts-path: ${{ steps.parse-info.outputs.artifactsPath }}
      deployment-type: ${{ steps.parse-info.outputs.deploymentType }}
      deployment-config: ${{ steps.parse-info.outputs.deploymentConfig }}

  - name: Verify deployment
    if: inputs.operation == 'verify'
    uses: ./.github/actions/verify-deployment
    with:
      app-name: ${{ steps.parse-info.outputs.appName }}
      environment: ${{ inputs.environment }}
      verification-url: ${{ steps.parse-info.outputs.verificationUrl }}
      timeout: ${{ steps.parse-info.outputs.timeout || '30' }}
      max-retries: ${{ steps.parse-info.outputs.maxRetries || '3' }}

  - name: Rollback deployment
    if: inputs.operation == 'rollback'
    uses: ./.github/actions/rollback-deployment
    with:
      app-name: ${{ steps.parse-info.outputs.appName }}
      environment: ${{ inputs.environment }}
      current-deployment: ${{ steps.parse-info.outputs.currentDeployment }}
      last-stable-commit: ${{ steps.parse-info.outputs.lastStableCommit }}
      deployment-type: ${{ steps.parse-info.outputs.deploymentType }}
      deployment-config: ${{ steps.parse-info.outputs.deploymentConfig }}

  - name: Set outputs
    id: set-outputs
    shell: bash
    run: |
      if [[ "${{ inputs.operation }}" == "deploy" ]]; then
        echo "operation-status=${{ steps.deploy-application.outputs.deployment-status }}" >> $GITHUB_OUTPUT
        echo "deployment-url=${{ steps.deploy-application.outputs.deployed-url }}" >> $GITHUB_OUTPUT
      elif [[ "${{ inputs.operation }}" == "verify" ]]; then
        echo "operation-status=${{ steps.verify-deployment.outputs.verification-status }}" >> $GITHUB_OUTPUT
        echo "verification-result=${{ steps.verify-deployment.outputs.verification-result }}" >> $GITHUB_OUTPUT
      elif [[ "${{ inputs.operation }}" == "rollback" ]]; then
        echo "operation-status=${{ steps.rollback-deployment.outputs.rollback-status }}" >> $GITHUB_OUTPUT
        echo "rollback-status=${{ steps.rollback-deployment.outputs.new-deployment-details }}" >> $GITHUB_OUTPUT
      fi

  - name: Notify on failure
    if: failure()
    uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      text: "Deployment operation failed for ${{ steps.parse-info.outputs.appName }} in ${{ inputs.environment }}"
      webhook_url: ${{ secrets.SLACK_WEBHOOK }}
