name: 'Update Dependencies'
description: 'Update project dependencies based on security and version checks'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  updates-list:
    description: 'List of updated dependencies'

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Update dependencies
    id: update-deps
    shell: bash
    run: |
      npm update
      UPDATES=$(npm outdated --json | jq -r 'to_entries | map("\(.key): \(.value.current) -> \(.value.latest)") | join(", ")')
      echo "updates-list=$UPDATES" >> $GITHUB_OUTPUT

  - name: Commit changes
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git add package.json package-lock.json
      git diff --quiet && git diff --staged --quiet || (git commit -m "Update dependencies" && git push)
