plugins:
  slack:
    webhook: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
    channels:
      performance_alerts: performance-alerts
      pr_updates: "#pr-updates"
      ci_alerts: ci-alerts
      security_alerts: "#security-alerts"
      repo_updates: repo-updates

  email:
    team: team@example.com
    security_team: security-team@example.com

  github:
    actions:
    - GitHub Actions
    pages:
      branch: gh-pages

  npm:
    audit: true

  snyk:
    enabled: false

  turbo:
    enabled: true

  chrome_web_store:
    extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
    client_id: ${{ secrets.CHROME_CLIENT_ID }}
    client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
    refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  swagger:
    enabled: true

  eslint:
    enabled: true

  prettier:
    enabled: true

  dependabot:
    enabled: true
    package_ecosystems:
    - npm
    - github-actions
    schedule:
      interval: weekly

  webhook:
    url: https://example.com/webhook
