security_dependency_management:
  schedule: "0 2 * * 1" # Weekly on Monday at 2 AM UTC
  security_check:
    tools:
    - npm audit
    fail_on: high
  dependency_update:
    enabled: true
    auto_merge: true
    ignore_dev_dependencies: false
  vulnerability_reporting:
    enabled: true
    issue_creation:
      enabled: true
      labels:
      - security
      - critical
  ai_analysis:
    enabled: true
    template: .github/templates/security_vulnerability_report_template.md
  update_security_policy:
    enabled: true
    policy_file: .github/SECURITY.md
