name: 'Validate Config'
description: 'Validates the existence and structure of the config.yml file in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  config-validation-status:
    description: 'Boolean indicating if the configuration is valid'

runs:
  using: 'composite'
  steps:
  - name: Install yq
    shell: bash
    run: |
      sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

  - name: Check config.yml existence
    shell: bash
    run: |
      if [ ! -f ".github/config.yml" ]; then
        echo "config-validation-status=false" >> $GITHUB_OUTPUT
        echo "::error::config.yml file not found in .github directory"
        exit 1
      fi

  - name: Validate YAML structure
    shell: bash
    run: |
      if ! yq eval '.github/config.yml' > /dev/null 2>&1; then
        echo "config-validation-status=false" >> $GITHUB_OUTPUT
        echo "::error::config.yml is not a valid YAML file"
        exit 1
      fi

  - name: Validate config structure
    shell: bash
    run: |
      required_keys=("repository" "issue_management" "pr_management" "release_management" "security_dependency_management" "metrics_generation" "packages" "plugins")
      for key in "${required_keys[@]}"; do
        if ! yq eval ".$key" .github/config.yml > /dev/null 2>&1; then
          echo "config-validation-status=false" >> $GITHUB_OUTPUT
          echo "::error::Required key '$key' not found in config.yml"
          exit 1
        fi
      done
      echo "config-validation-status=true" >> $GITHUB_OUTPUT
