name: 'Validate Config'
description: 'Validates the existence and structure of the config.yml file in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  config-validation-status:
    description: 'Boolean indicating if the configuration is valid'
  installation-status:
    description: 'Status of the installation process'

runs:
  using: 'composite'
  steps:
  - name: Check package manager
    shell: bash
    run: |
      if [ "yarn" = "npm" ]; then
        echo "installation-status=success" >> $GITHUB_OUTPUT
      fi

  - name: Validate config
    shell: bash
    run: |
      CONFIG_PATH='.github/config.yml'

      if [ ! -f "$CONFIG_PATH" ]; then
        echo "::error::config.yml file not found in .github directory"
        echo "config-validation-status=false" >> $GITHUB_OUTPUT
        exit 1
      fi

      REQUIRED_KEYS=("repository" "issue_management" "pr_management" "release_management" "security_dependency_management" "metrics_generation" "packages" "plugins")

      for key in "${REQUIRED_KEYS[@]}"; do
        if ! grep -q "^$key:" "$CONFIG_PATH"; then
          echo "::error::Required key '$key' not found in config.yml"
          echo "config-validation-status=false" >> $GITHUB_OUTPUT
          exit 1
        fi
      done

      echo "config-validation-status=true" >> $GITHUB_OUTPUT
