name: 'Validate Config'
description: 'Validates the existence and structure of the config.yml file in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  config-validation-status:
    description: 'Boolean indicating if the configuration is valid'

runs:
  using: 'composite'
  steps:
  - name: Check config.yml existence
    shell: bash -l {0}
    run: |
      if [ ! -f ".github/config.yml" ]; then
        echo "config-validation-status=false" >> $GITHUB_OUTPUT
        echo "::error::config.yml file not found in .github directory"
        exit 1
      fi

  - name: Validate YAML structure
    shell: bash -l {0}
    run: |
      if ! yq eval '.github/config.yml' > /dev/null 2>&1; then
        echo "config-validation-status=false" >> $GITHUB_OUTPUT
        echo "::error::config.yml is not a valid YAML file"
        exit 1
      else
        echo "config-validation-status=true" >> $GITHUB_OUTPUT
      fi

  - name: Install yq
    shell: bash -l {0}
    run: |
      sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
