name: 'Create Dependency Update PRs'
description: 'Creates pull requests for dependency updates'

inputs:
  update-report:
    description: 'Report of available updates from check-dependency-updates'
    required: true
  vulnerability-report:
    description: 'Report of vulnerabilities from security-vulnerability-scan'
    required: true

outputs:
  created-prs:
    description: 'List of created pull requests'
  pr-creation-summary:
    description: 'Summary of the pull request creation operation'

runs:
  using: 'node20'
  main: 'index.js'

jobs:
  create-update-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Debug - Input values
      run: |
        echo "Update report: ${{ inputs.update-report }}"
        echo "Vulnerability report: ${{ inputs.vulnerability-report }}"

    - name: Create update branches and PRs
      id: create-prs
      run: |
        update_report='${{ inputs.update-report }}'
        vulnerability_report='${{ inputs.vulnerability-report }}'

        created_prs=()
        for update_type in major minor patch
        do
          updates=$(echo $update_report | jq -r ".$update_type[]")
          for update in $updates
          do
            package=$(echo $update | cut -d: -f1)
            version=$(echo $update | cut -d: -f2 | cut -d'>' -f2 | tr -d ' ')
            branch_name="dependency-update/$package-$version"
            git checkout -b $branch_name

            # Update dependency version (this is a simplified example)
            sed -i "s/\"$package\": \".*\"/\"$package\": \"$version\"/" package.json

            git add package.json
            git commit -m "Update $package to version $version"
            git push origin $branch_name

            pr_title="Update $package to version $version"
            pr_body="This PR updates $package to version $version."
            pr_url=$(gh pr create --title "$pr_title" --body "$pr_body" --base main)

            created_prs+=("$pr_url")

            git checkout main
          done
        done

        echo "::set-output name=created-prs::$(echo "${created_prs[@]}" | jq -R -s -c 'split(" ")')"

    - name: Debug - Created PRs
      run: |
        echo "Created PRs: ${{ steps.create-prs.outputs.created-prs }}"

    - name: Generate PR creation summary
      id: pr-summary
      run: |
        summary="Created $(echo '${{ steps.create-prs.outputs.created-prs }}' | jq length) pull requests for dependency updates."
        echo "::set-output name=pr-creation-summary::$summary"

    - name: Debug - PR creation summary
      run: |
        echo "PR creation summary: ${{ steps.pr-summary.outputs.pr-creation-summary }}"
