name: 'Create Issues'
description: 'Creates GitHub issues based on provided data'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  issues-data:
    description: 'JSON string containing data for creating issues'
    required: true

outputs:
  created-issues:
    description: 'JSON array of created issue numbers'

runs:
  using: 'composite'
  steps:
  - name: Debug Input
    shell: bash -l {0}
    run: |
      echo "Debug: Input issues-data"
      echo "${{ inputs.issues-data }}"

  - name: Create Issues
    id: create-issues
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      ISSUES_DATA: ${{ inputs.issues-data }}
    run: |
      echo "Debug: Starting issue creation process"
      created_issues=()

      while IFS= read -r issue; do
        title=$(echo "$issue" | jq -r '.title')
        body=$(echo "$issue" | jq -r '.body')
        labels=$(echo "$issue" | jq -r '.labels | join(",")')
        assignees=$(echo "$issue" | jq -r '.assignees | join(",")')

        echo "Debug: Creating issue: $title"

        response=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/issues" \
          -d "{\"title\":\"$title\",\"body\":\"$body\",\"labels\":[$labels],\"assignees\":[$assignees]}")

        issue_number=$(echo "$response" | jq -r '.number')

        if [ "$issue_number" != "null" ]; then
          echo "Debug: Created issue #$issue_number: $title"
          created_issues+=("$issue_number")
        else
          echo "Debug: Error creating issue: $title"
          echo "Response: $response"
        fi
      done < <(echo "$ISSUES_DATA" | jq -c '.[]')

      created_issues_json=$(printf '%s\n' "${created_issues[@]}" | jq -R . | jq -s .)
      echo "created-issues=$created_issues_json" >> $GITHUB_OUTPUT

      echo "Debug: All issues created. Created issues: $created_issues_json"

  - name: Debug Output
    shell: bash -l {0}
    run: |
      echo "Debug: Output created-issues"
      echo "${{ steps.create-issues.outputs.created-issues }}"

  - name: Error Handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "Debug: An error occurred during the issue creation process"
      echo "created-issues=[]" >> $GITHUB_OUTPUT
