name: 'Review Stale PRs'
description: 'Reviews and manages stale pull requests'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  stale-threshold:
    description: 'Number of days after which a PR is considered stale'
    required: true

outputs:
  stale-prs-count:
    description: 'Number of stale PRs found'
  stale-prs-report:
    description: 'Report of stale PRs'

runs:
  using: "composite"
  steps:
  - name: Debug Inputs
    shell: bash -l {0}
    run: |
      echo "Debug: Stale Threshold - ${{ inputs.stale-threshold }}"

  - name: Fetch and Process Stale PRs
    id: fetch-process-prs
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      STALE_THRESHOLD: ${{ inputs.stale-threshold }}
    run: |
      stale_date=$(date -d "$STALE_THRESHOLD days ago" +%Y-%m-%d)
      echo "Debug: Stale date threshold - $stale_date"

      stale_prs=$(gh pr list --json number,title,url,updatedAt --limit 1000 | jq --arg date "$stale_date" '[.[] | select(.updatedAt < $date)]')
      stale_prs_count=$(echo "$stale_prs" | jq length)
      echo "stale-prs-count=$stale_prs_count" >> $GITHUB_OUTPUT

      echo "Debug: Found $stale_prs_count stale PRs"

      for pr in $(echo "$stale_prs" | jq -c '.[]'); do
        number=$(echo $pr | jq -r '.number')
        title=$(echo $pr | jq -r '.title')
        url=$(echo $pr | jq -r '.url')

        echo "Debug: Processing stale PR #$number"

        gh pr edit $number --add-label "stale"
        gh pr comment $number --body "This pull request has been marked as stale due to lack of recent activity. Please update or close this PR if it's no longer relevant."

        assignees=$(gh pr view $number --json assignees | jq -r '.assignees[].login')
        if [ ! -z "$assignees" ]; then
          echo "Debug: Notifying assignees for PR #$number"
          assignee_mentions=$(echo $assignees | sed 's/\S\+/@&/g')
          gh pr comment $number --body "$assignee_mentions This PR requires your attention as it has become stale."
        fi
      done

      report=$(echo "$stale_prs" | jq -r '.[] | "- [#\(.number)](\(.url)): \(.title)"' | sed ':a;N;$!ba;s/\n/\\n/g')
      echo "stale-prs-report<<EOF" >> $GITHUB_OUTPUT
      echo "$report" >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT

  - name: Create Stale PR Report Issue
    if: steps.fetch-process-prs.outputs.stale-prs-count != '0'
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: |
      issue_title="Weekly Stale PR Report"
      issue_body="## Stale Pull Requests Report\n\n${{ steps.fetch-process-prs.outputs.stale-prs-report }}"
      gh issue create --title "$issue_title" --body "$issue_body" --label "report,maintenance"

  - name: Error Handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "Debug: An error occurred during the stale PR review process"
      echo "Please check the workflow logs for more details"
