name: 'Review Stale PRs'
description: 'Reviews and manages stale pull requests'

inputs:
  stale-threshold:
    description: 'Number of days after which a PR is considered stale'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Debug Inputs
    shell: bash
    run: |
      echo "Debug: Stale Threshold - ${{ inputs.stale-threshold }}"

  - name: Fetch Stale PRs
    id: fetch-stale-prs
    uses: actions/github-script@v6
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        console.log('Debug: Starting to fetch stale PRs');
        const staleThreshold = parseInt('${{ inputs.stale-threshold }}');
        const staleDate = new Date();
        staleDate.setDate(staleDate.getDate() - staleThreshold);

        console.log(`Debug: Stale date threshold - ${staleDate.toISOString()}`);

        const { data: pullRequests } = await github.rest.pulls.list({
          owner: context.repo.owner,
          repo: context.repo.repo,
          state: 'open',
          sort: 'updated',
          direction: 'asc'
        });

        console.log(`Debug: Total open PRs - ${pullRequests.length}`);

        const stalePRs = pullRequests.filter(pr => new Date(pr.updated_at) < staleDate);
        console.log(`Debug: Found ${stalePRs.length} stale PRs`);
        return JSON.stringify(stalePRs);

  - name: Debug Fetched PRs
    shell: bash
    run: |
      echo "Debug: Fetched Stale PRs"
      echo "${{ steps.fetch-stale-prs.outputs.result }}"

  - name: Process Stale PRs
    uses: actions/github-script@v6
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        console.log('Debug: Starting to process stale PRs');
        const stalePRs = JSON.parse('${{ steps.fetch-stale-prs.outputs.result }}');

        for (const pr of stalePRs) {
          console.log(`Debug: Processing stale PR #${pr.number}`);

          console.log(`Debug: Adding 'stale' label to PR #${pr.number}`);
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            labels: ['stale']
          });

          console.log(`Debug: Posting comment on PR #${pr.number}`);
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            body: 'This pull request has been marked as stale due to lack of recent activity. Please update or close this PR if it's no longer relevant.'
          });

          if (pr.assignees.length > 0) {
            console.log(`Debug: Notifying assignees for PR #${pr.number}`);
            const assignees = pr.assignees.map(a => `@${a.login}`).join(' ');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `${assignees} This PR requires your attention as it has become stale.`
            });
          }
        }
        console.log('Debug: Finished processing stale PRs');

  - name: Generate Stale PR Report
    id: generate-report
    uses: actions/github-script@v6
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        console.log('Debug: Generating stale PR report');
        const stalePRs = JSON.parse('${{ steps.fetch-stale-prs.outputs.result }}');
        const report = stalePRs.map(pr => `- [#${pr.number}](${pr.html_url}): ${pr.title}`).join('\n');
        console.log(`Debug: Generated report with ${stalePRs.length} PRs`);
        return report;

  - name: Debug Generated Report
    shell: bash
    run: |
      echo "Debug: Generated Stale PR Report"
      echo "${{ steps.generate-report.outputs.result }}"

  - name: Create Stale PR Report Issue
    if: steps.generate-report.outputs.result != ''
    uses: ./.github/actions/create-issue
    with:
      issue-type: 'Stale PR Report'
      issue-title: 'Weekly Stale PR Report'
      issue-details: ${{ steps.generate-report.outputs.result }}
      issue-template: .github/templates/stale_pr_report_template.md
      labels: '["report", "maintenance"]'

  - name: Debug Issue Creation
    if: steps.generate-report.outputs.result != ''
    shell: bash
    run: |
      echo "Debug: Stale PR Report Issue created"

  - name: Error Handling
    if: failure()
    run: |
      echo "Debug: An error occurred during the stale PR review process"
      echo "Please check the workflow logs for more details"
    shell: bash
