name: 'Commit Changes'
description: 'Commits changes to the repository'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  files:
    description: 'Space-separated list of files to commit'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Setup Git
    shell: bash
    run: |
      echo "Setting up Git configuration..."
      git config user.name github-actions
      git config user.email github-actions@github.com
      echo "Git configuration complete."

  - name: Commit changes
    id: commit
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      COMMIT_MESSAGE: ${{ inputs.commit-message }}
      FILES: ${{ inputs.files }}
    run: |
      echo "Starting commit process..."
      echo "Files to be committed: $FILES"

      git add $FILES
      echo "Files added to staging area."

      git status
      echo "Current Git status shown above."

      git commit -m "$COMMIT_MESSAGE"
      echo "Changes committed locally."

      echo "Pushing changes to remote repository..."
      git push

      COMMIT_SHA=$(git rev-parse HEAD)
      echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

      echo "Changes committed and pushed successfully."
      echo "Commit SHA: $COMMIT_SHA"

outputs:
  commit-sha:
    description: 'The SHA of the commit'
    value: ${{ steps.commit.outputs.commit-sha }}
