import { logger } from '../../utils/logger';
import { ThemeVariables } from "../hooks/use-theme-costomizer";

/**
 * Exports the current theme as a CSS file.
 * 
 * This function is part of the ShadCN Theme Customizer browser extension.
 * ShadCN Theme Customizer allows you to customize and export themes for websites using ShadCN UI.
 * 
 * GitHub: https://github.com/your-username/shadcn-theme-customizer
 * Chrome Web Store: https://chrome.google.com/webstore/detail/shadcn-theme-customizer/your-extension-id
 * 
 * @license MIT
 * @copyright (c) 2023 Your Name
 * 
 * @param {ThemeVariables} currentTheme - The current theme variables to export.
 * @param {ThemeVariables} originalTheme - The original theme variables.
 * @param {'light' | 'dark'} currentMode - The current theme mode.
 */
export function exportTheme(currentTheme: ThemeVariables, originalTheme: ThemeVariables, currentMode: 'light' | 'dark'): void {
  logger.info('Exporting theme', { currentTheme, originalTheme, currentMode });

  const generateCssVariables = (variables: ThemeVariables) => {
    return Object.entries(variables)
      .map(([key, value]) => `    --${key}: ${value};`)
      .join('\n');
  };

  const mergedTheme = { ...originalTheme, ...currentTheme };

  const cssContent = `/**
 * Generated by ShadCN Theme Customizer
 * https://github.com/your-username/shadcn-theme-customizer
 *
 * This theme is compatible with ShadCN UI (https://ui.shadcn.com/)
 * Learn more about customizing your ShadCN UI theme:
 * https://ui.shadcn.com/docs/theming
 *
 * How to use this theme:
 * 1. Copy this file to your project's styles directory.
 * 2. Import this file in your global CSS or in your root layout.
 * 3. Enjoy your customized ShadCN UI theme!
 */

@layer base {
  :root {
${generateCssVariables(currentMode === 'light' ? mergedTheme : originalTheme)}
  }

  .dark {
${generateCssVariables(currentMode === 'dark' ? mergedTheme : originalTheme)}
  }
}
`;

  const blob = new Blob([cssContent], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  
  logger.debug('Created Blob URL for theme CSS', { url });

  const a = document.createElement('a');
  a.href = url;
  a.download = 'shadcn-theme-customizer.css';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  logger.info('Theme exported successfully');
}
