name: Setup CODEOWNERS

description: Configures CODEOWNERS file for the repository

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository-admins:
    description: 'JSON array of repository administrators'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Install dependencies
    shell: bash
    run: |
      npm install @octokit/rest

  - name: Configure CODEOWNERS
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      REPOSITORY_ADMINS: ${{ inputs.repository-admins }}
    run: |
      node -e '
      const { Octokit } = require("@octokit/rest");
      const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
      const admins = JSON.parse(process.env.REPOSITORY_ADMINS);

      async function setupCodeowners() {
        const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
        const codeownersContent = `# This file is maintained automatically by "GitHub Repository Setup Workflow"
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# ${admins.join(", ")} will be requested for
# review when someone opens a pull request.
*       ${admins.map(admin => `@${admin}`).join(" ")}
`;

        try {
          await octokit.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: "CODEOWNERS",
            message: "Update CODEOWNERS file",
            content: Buffer.from(codeownersContent).toString("base64"),
            branch: "main"
          });
          console.log("CODEOWNERS file created/updated successfully");
        } catch (error) {
          console.error("Error updating CODEOWNERS file:", error);
          process.exit(1);
        }
      }

      setupCodeowners().catch(console.error);
      '

outputs:
  codeowners-updated:
    description: 'Indicates whether the CODEOWNERS file was successfully updated'
    value: ${{ steps.configure-codeowners.outputs.codeowners-updated }}
