name: Setup CODEOWNERS
description: Configures CODEOWNERS file for the repository

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository-admins:
    description: 'JSON array of repository administrators'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Configure CODEOWNERS
    id: configure-codeowners
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      REPOSITORY_ADMINS: ${{ inputs.repository-admins }}
    run: |
      # Parse repository admins
      IFS=',' read -ra ADMINS <<< "$(echo "$REPOSITORY_ADMINS" | jq -r '.[]')"

      # Generate CODEOWNERS content
      CODEOWNERS_CONTENT="# This file is maintained automatically by \"GitHub Repository Setup Workflow\"\n"
      CODEOWNERS_CONTENT+="# These owners will be the default owners for everything in\n"
      CODEOWNERS_CONTENT+="# the repo. Unless a later match takes precedence,\n"
      CODEOWNERS_CONTENT+="# ${ADMINS[*]} will be requested for\n"
      CODEOWNERS_CONTENT+="# review when someone opens a pull request.\n"
      CODEOWNERS_CONTENT+="*       ${ADMINS[@]/#/@}"

      # Write CODEOWNERS file
      echo -e "$CODEOWNERS_CONTENT" > CODEOWNERS

      # Commit and push changes
      git config user.name "GitHub Action"
      git config user.email "action@github.com"
      git add CODEOWNERS
      git commit -m "Update CODEOWNERS file"
      git push

      echo "codeowners-updated=true" >> $GITHUB_OUTPUT

outputs:
  codeowners-updated:
    description: 'Indicates whether the CODEOWNERS file was successfully updated'
    value: ${{ steps.configure-codeowners.outputs.codeowners-updated }}
