name: 'Create Issues'
description: 'Creates GitHub issues based on provided data'

inputs:
  issues-data:
    description: 'JSON string containing data for creating issues'
    required: true

outputs:
  created-issues:
    description: 'JSON array of created issue numbers'

runs:
  using: 'composite'
  steps:
  - name: Debug Input
    shell: bash -l {0}
    run: |
      echo "Debug: Input issues-data"
      echo "${{ inputs.issues-data }}"

  - name: Create Issues
    id: create-issues
    uses: actions/github-script@v6
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      script: |
        console.log('Debug: Starting issue creation process');
        const issuesData = JSON.parse('${{ inputs.issues-data }}');
        console.log('Debug: Parsed issues data:', JSON.stringify(issuesData, null, 2));
        const createdIssues = [];

        for (const issue of issuesData) {
          try {
            console.log('Debug: Creating issue:', JSON.stringify(issue, null, 2));
            const { data: createdIssue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue.title,
              body: issue.body,
              labels: issue.labels || [],
              assignees: issue.assignees || []
            });
            console.log(`Debug: Created issue #${createdIssue.number}: ${createdIssue.title}`);
            createdIssues.push(createdIssue.number);
          } catch (error) {
            console.error(`Debug: Error creating issue: ${error.message}`);
            console.error(error.stack);
          }
        }

        console.log('Debug: All issues created. Created issues:', JSON.stringify(createdIssues));
        core.setOutput('created-issues', JSON.stringify(createdIssues));

  - name: Debug Output
    shell: bash -l {0}
    run: |
      echo "Debug: Output created-issues"
      echo "${{ steps.create-issues.outputs.created-issues }}"

  - name: Error Handling
    if: failure()
    run: |
      echo "Debug: An error occurred during the issue creation process"
      echo "created-issues=[]" >> $GITHUB_OUTPUT
    shell: bash -l {0}

