name: 'Determine Affected Packages'
description: 'Identifies packages affected by changes in the repository'

inputs:
  changed_files:
    description: 'JSON array of changed files'
    required: true
  apps_configuration:
    description: 'JSON object containing app configurations'
    required: true

outputs:
  affected_apps:
    description: 'JSON array of affected app names'
    value: ${{ steps.determine-affected.outputs.affected_apps }}

runs:
  using: 'composite'
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '16'

  - name: Install dependencies
    shell: bash -l {0}
    run: |
      npm install --global jq

  - name: Determine affected packages
    id: determine-affected
    shell: bash -l {0}
    run: |
      # Parse inputs
      changed_files=$(echo '${{ inputs.changed_files }}' | jq -r '.[]')
      apps_config='${{ inputs.apps_configuration }}'

      # Initialize an empty array for affected apps
      affected_apps=()

      # Loop through each changed file
      while IFS= read -r file; do
        # Check each app's directory
        echo "$apps_config" | jq -c '.[]' | while read -r app; do
          app_name=$(echo "$app" | jq -r '.name')
          app_dir=$(echo "$app" | jq -r '.directory')

          # If the changed file is in the app's directory, add the app to affected_apps
          if [[ "$file" == "$app_dir"* ]]; then
            if [[ ! " ${affected_apps[@]} " =~ " ${app_name} " ]]; then
              affected_apps+=("$app_name")
            fi
          fi
        done
      done <<< "$changed_files"

      # Convert affected_apps array to JSON
      affected_apps_json=$(printf '%s\n' "${affected_apps[@]}" | jq -R . | jq -s .)

      # Set output
      echo "affected_apps=$affected_apps_json" >> $GITHUB_OUTPUT

      # Debug output
      echo "Affected apps: $affected_apps_json"

  - name: Error handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "An error occurred while determining affected packages."
      echo "affected_apps=[]" >> $GITHUB_OUTPUT
