name: 'Security Vulnerability Scan'
description: 'Scans project dependencies for known security vulnerabilities'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  working-directory:
    description: 'Directory to run security checks in'
    required: false
    default: '.'

outputs:
  vulnerability-report:
    description: 'Detailed report of found vulnerabilities'
  affected-dependencies:
    description: 'List of dependencies affected by vulnerabilities'

runs:
  using: "composite"
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Install security scanning tools
    shell: bash
    run: |
      sudo npm install -g npm-audit-html snyk
      pip install safety

  - name: Run npm audit
    id: npm-audit
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      npm audit --json > npm-audit-results.json
      npm-audit-html -o npm-audit-report.html

  - name: Run Snyk scan
    id: snyk-scan
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      SNYK_TOKEN: ${{ inputs.github-token }}
    run: |
      snyk test --json > snyk-results.json

  - name: Run safety check
    id: safety-check
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      safety check --json > safety-results.json

  - name: Compile vulnerability report
    id: compile-report
    shell: python
    working-directory: ${{ inputs.working-directory }}
    run: |
      import json
      import os

      with open('npm-audit-results.json', 'r') as f:
        npm_audit = json.load(f)
      with open('snyk-results.json', 'r') as f:
        snyk_results = json.load(f)
      with open('safety-results.json', 'r') as f:
        safety_results = json.load(f)

      vulnerability_report = {
          "npm_audit": npm_audit,
          "snyk": snyk_results,
          "safety": safety_results
      }

      affected_dependencies = set()
      for vuln in npm_audit.get('vulnerabilities', {}).values():
          affected_dependencies.add(vuln['module_name'])
      for vuln in snyk_results.get('vulnerabilities', []):
          affected_dependencies.add(vuln['package'])
      for vuln in safety_results:
          affected_dependencies.add(vuln['package'])

      with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          print(f"vulnerability-report={json.dumps(vulnerability_report)}", file=f)
          print(f"affected-dependencies={json.dumps(list(affected_dependencies))}", file=f)

  - name: Output results
    shell: bash
    run: |
      echo "Vulnerability report: ${{ steps.compile-report.outputs.vulnerability-report }}"
      echo "Affected dependencies: ${{ steps.compile-report.outputs.affected-dependencies }}"
