name: 'Security Vulnerability Scan'
description: 'Scans project dependencies for known security vulnerabilities'

inputs:
  current-dependencies:
    description: 'List of current project dependencies'
    required: true
  vulnerability-databases:
    description: 'List of vulnerability databases to use for scanning'
    required: true

outputs:
  vulnerability-report:
    description: 'Detailed report of found vulnerabilities'
  affected-dependencies:
    description: 'List of dependencies affected by vulnerabilities'

runs:
  using: 'node20'
  main: 'index.js'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Debug - Input values
      run: |
        echo "Current dependencies: ${{ inputs.current-dependencies }}"
        echo "Vulnerability databases: ${{ inputs.vulnerability-databases }}"

    - name: Install security scanning tools
      run: |
        npm install -g npm-audit-html snyk
        pip install safety

    - name: Run npm audit
      id: npm-audit
      run: |
        npm audit --json > npm-audit-results.json
        npm-audit-html -o npm-audit-report.html

    - name: Debug - npm audit results
      run: cat npm-audit-results.json

    - name: Run Snyk scan
      id: snyk-scan
      run: |
        snyk test --json > snyk-results.json

    - name: Debug - Snyk scan results
      run: cat snyk-results.json

    - name: Run safety check
      id: safety-check
      run: |
        safety check --json > safety-results.json

    - name: Debug - Safety check results
      run: cat safety-results.json

    - name: Compile vulnerability report
      id: compile-report
      run: |
        python3 << EOF
        import json
        import os

        npm_audit = json.load(open('npm-audit-results.json'))
        snyk_results = json.load(open('snyk-results.json'))
        safety_results = json.load(open('safety-results.json'))

        vulnerability_report = {
            "npm_audit": npm_audit,
            "snyk": snyk_results,
            "safety": safety_results
        }

        affected_dependencies = set()
        for vuln in npm_audit.get('vulnerabilities', {}).values():
            affected_dependencies.add(vuln['module_name'])
        for vuln in snyk_results.get('vulnerabilities', []):
            affected_dependencies.add(vuln['package'])
        for vuln in safety_results:
            affected_dependencies.add(vuln['package'])

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f"vulnerability-report={json.dumps(vulnerability_report)}", file=f)
            print(f"affected-dependencies={json.dumps(list(affected_dependencies))}", file=f)
        EOF

    - name: Debug - Compiled vulnerability report
      run: |
        echo "Vulnerability report: ${{ steps.compile-report.outputs.vulnerability-report }}"
        echo "Affected dependencies: ${{ steps.compile-report.outputs.affected-dependencies }}"
