name: 'Setup Repository Branches'
description: 'Creates or updates multiple branches in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  branches:
    description: 'JSON array of branch names to create or update'
    required: true
  base-branch:
    description: 'Name of the base branch'
    required: true
    default: 'main'

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
    with:
      token: ${{ inputs.github-token }}
      fetch-depth: 0

  - name: Parse branches
    id: parse-branches
    shell: bash
    run: |
      echo "branches=$(echo '${{ inputs.branches }}' | jq -c '.')" >> $GITHUB_OUTPUT

  - name: Setup branches
    shell: bash
    run: |
      for branch in $(echo '${{ inputs.branches }}' | jq -r '.[]'); do
        if git ls-remote --exit-code --heads origin $branch; then
          echo "Branch $branch already exists. Updating..."
          git checkout $branch
          git pull origin ${{ inputs.base-branch }}
        else
          echo "Creating new branch $branch..."
          git checkout -b $branch ${{ inputs.base-branch }}
        fi
        git push -u origin $branch
      done

  - name: Check branch setup status
    if: failure()
    shell: bash
    run: |
      echo "An error occurred during branch setup"

  - name: Summarize branch setup
    shell: bash
    run: |
      echo "Branch setup completed"
      echo "Successfully processed branches: ${{ inputs.branches }}"
