name: 'Send Webhook'
description: 'Sends a webhook to a specified URL with custom payload'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  webhook-url:
    description: 'URL to send the webhook to'
    required: true
  payload:
    description: 'JSON string of the payload to send'
    required: true
  custom-headers:
    description: 'JSON string of custom headers to include'
    required: false
    default: '{}'

outputs:
  status-code:
    description: 'HTTP status code of the webhook response'
  response-body:
    description: 'Body of the webhook response'

runs:
  using: "composite"
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Send webhook
    id: send-webhook
    shell: bash -l {0}
    run: |
      response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ inputs.github-token }}" -H "${{ inputs.custom-headers }}" -d '${{ inputs.payload }}' -w "\n%{http_code}" "${{ inputs.webhook-url }}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      echo "status-code=$status_code" >> $GITHUB_OUTPUT
      echo "response-body=$response_body" >> $GITHUB_OUTPUT

  - name: Set outputs
    id: set-outputs
    shell: bash -l {0}
    run: |
      echo "status-code=${{ steps.send-webhook.outputs.status-code }}" >> $GITHUB_OUTPUT
      echo "response-body=${{ steps.send-webhook.outputs.response-body }}" >> $GITHUB_OUTPUT
