name: 'Update Issue'
description: 'Updates an existing GitHub issue with new content'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  issue-number:
    description: 'The number of the issue to update'
    required: true
  comment-body:
    description: 'The content to add as a comment to the issue'
    required: false
  update-body:
    description: 'Whether to update the issue body'
    required: false
    default: 'false'
  body-update:
    description: 'The content to update in the issue body'
    required: false

outputs:
  update-status:
    description: 'Status of the update operation'

runs:
  using: 'composite'
  steps:
  - name: Debug inputs
    shell: bash -l {0}
    run: |
      echo "Debug: Input values"
      echo "issue-number: ${{ inputs.issue-number }}"
      echo "comment-body: ${{ inputs.comment-body }}"
      echo "update-body: ${{ inputs.update-body }}"
      echo "body-update: ${{ inputs.body-update }}"

  - name: Update issue
    id: update-issue
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      ISSUE_NUMBER: ${{ inputs.issue-number }}
      COMMENT_BODY: ${{ inputs.comment-body }}
      UPDATE_BODY: ${{ inputs.update-body }}
      BODY_UPDATE: ${{ inputs.body-update }}
    run: |
      if [ -n "$COMMENT_BODY" ]; then
        gh issue comment $ISSUE_NUMBER --body "$COMMENT_BODY"
        echo "Comment added successfully"
      fi

      if [ "$UPDATE_BODY" = "true" ] && [ -n "$BODY_UPDATE" ]; then
        CURRENT_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
        NEW_BODY="${CURRENT_BODY}

      $BODY_UPDATE"
        gh issue edit $ISSUE_NUMBER --body "$NEW_BODY"
        echo "Issue body updated successfully"
      fi

      echo "update-status=success" >> $GITHUB_OUTPUT

  - name: Error handling
    if: failure()
    shell: bash -l {0}
    run: |
      echo "An error occurred during the issue update process"
      echo "update-status=failure" >> $GITHUB_OUTPUT
