name: 'Setup Issue Labels'
description: 'Creates or updates issue labels in the repository'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  labels:
    description: 'JSON array of label objects to create or update'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Create or update labels
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      LABELS: ${{ inputs.labels }}
    run: |
      labels=$(echo "$LABELS" | jq -c '.[]')

      while IFS= read -r label; do
        name=$(echo "$label" | jq -r '.name')
        color=$(echo "$label" | jq -r '.color')
        description=$(echo "$label" | jq -r '.description')

        # Check if label exists
        if gh label list | grep -q "$name"; then
          # Update existing label
          gh label edit "$name" --color "$color" --description "$description"
          echo "Updated label: $name"
        else
          # Create new label
          gh label create "$name" --color "$color" --description "$description"
          echo "Created label: $name"
        fi
      done <<< "$labels"

outputs:
  labels-updated:
    description: 'Number of labels updated or created'
    value: ${{ steps.create-update-labels.outputs.labels-count }}
