name: 'Setup Context and Prerequisites'
description: 'Set up necessary context and prerequisites for the workflow'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  repository-context:
    description: 'JSON object containing repository context'
  config-data:
    description: 'Parsed configuration data'
  environment-variables:
    description: 'Set environment variables'
  package-manager:
    description: 'Detected package manager'
  installation-status:
    description: 'Status of the installation process'

runs:
  using: "composite"
  steps:
  - name: Detect package manager
    id: detect-package-manager
    shell: bash
    run: |
      if [ -f "package-lock.json" ]; then
        echo "package-manager=npm" >> $GITHUB_OUTPUT
      elif [ -f "yarn.lock" ]; then
        echo "package-manager=yarn" >> $GITHUB_OUTPUT
      elif [ -f "pnpm-lock.yaml" ]; then
        echo "package-manager=pnpm" >> $GITHUB_OUTPUT
      else
        echo "::error::No package manager lock file found"
        exit 1
      fi

  - name: Check package manager
    shell: bash
    run: |
      if [ "yarn" = "npm" ]; then
        echo "installation-status=success" >> $GITHUB_OUTPUT
      fi

  - name: Install dependencies
    uses: ./.github/actions/install-dependencies
    with:
      package-manager: ${{ steps.detect-package-manager.outputs.package-manager }}
      cache-key: ${{ runner.OS }}-${{ steps.detect-package-manager.outputs.package-manager }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
      github-token: ${{ inputs.github-token }}

  - name: Fetch repository metadata
    id: repo-metadata
    uses: actions/github-script@v7
    with:
      github-token: ${{ inputs.github-token }}
      script: |
        const { owner, repo } = context.repo;
        try {
          const repoData = await github.rest.repos.get({ owner, repo });
          return repoData.data;
        } catch (error) {
          core.setFailed(`Failed to fetch repository metadata: ${error.message}`);
        }

  - name: Load and parse config.yml
    id: config
    uses: actions/github-script@v7
    with:
      github-token: ${{ inputs.github-token }}
      script: |
        const fs = require('fs');
        const yaml = require('js-yaml');

        const CONFIG_PATH = '.github/config.yml';

        try {
          if (!fs.existsSync(CONFIG_PATH)) {
            core.setFailed('config.yml is missing');
            return;
          }

          const configContent = fs.readFileSync(CONFIG_PATH, 'utf8');
          const config = yaml.load(configContent);

          core.setOutput('config-data', JSON.stringify(config));
        } catch (error) {
          core.setFailed(`Error loading or parsing config.yml: ${error.message}`);
        }

  - name: Set up environment variables
    id: set-env-vars
    shell: bash
    run: |
      echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
      echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
      echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
      echo "GITHUB_REF=${{ github.ref }}" >> $GITHUB_ENV
      echo "PACKAGE_MANAGER=${{ steps.detect-package-manager.outputs.package-manager }}" >> $GITHUB_ENV

      CONFIG_DATA='${{ steps.config.outputs.config-data }}'
      REPO_TYPE=$(echo "$CONFIG_DATA" | jq -r '.repository.type')
      MAIN_BRANCHES=$(echo "$CONFIG_DATA" | jq -r '.version_control.main_branches')

      echo "REPO_TYPE=$REPO_TYPE" >> $GITHUB_ENV
      echo "MAIN_BRANCHES=$MAIN_BRANCHES" >> $GITHUB_ENV

      echo "environment-variables=Environment variables set" >> $GITHUB_OUTPUT

  - name: Validate repository settings
    shell: bash
    run: |
      REPO_METADATA='${{ steps.repo-metadata.outputs.result }}'
      CONFIG_DATA='${{ steps.config.outputs.config-data }}'

      HAS_ISSUES=$(echo "$REPO_METADATA" | jq -r '.has_issues')
      HAS_PROJECTS=$(echo "$REPO_METADATA" | jq -r '.has_projects')
      AUTO_LABELING=$(echo "$CONFIG_DATA" | jq -r '.issue_management.auto_labeling.enabled')
      REPO_TYPE=$(echo "$CONFIG_DATA" | jq -r '.repository.type')

      if [ "$HAS_ISSUES" = "false" ] && [ "$AUTO_LABELING" = "true" ]; then
        echo "::warning::Issues are not enabled for this repository, but issue management is configured"
      fi

      if [ "$HAS_PROJECTS" = "false" ] && [ "$REPO_TYPE" = "monorepo" ]; then
        echo "::warning::Projects are not enabled for this repository, but it is configured as a monorepo"
      fi

  - name: Determine current branch and commit information
    shell: bash
    run: |
      CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
      CURRENT_COMMIT=$GITHUB_SHA
      echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
      echo "CURRENT_COMMIT=$CURRENT_COMMIT" >> $GITHUB_ENV

  - name: Create repository context
    id: repo-context
    shell: bash
    run: |
      REPO_METADATA='${{ steps.repo-metadata.outputs.result }}'
      CONFIG_DATA='${{ steps.config.outputs.config-data }}'
      CONTEXT=$(jq -n \
        --argjson repoMetadata "$REPO_METADATA" \
        --argjson config "$CONFIG_DATA" \
        --arg branch "$CURRENT_BRANCH" \
        --arg commit "$CURRENT_COMMIT" \
        --arg repoType "$REPO_TYPE" \
        --argjson mainBranches "$MAIN_BRANCHES" \
        --arg packageManager "${{ steps.detect-package-manager.outputs.package-manager }}" \
        '{
          repoMetadata: $repoMetadata,
          config: $config,
          branch: $branch,
          commit: $commit,
          repoType: $repoType,
          mainBranches: $mainBranches,
          packageManager: $packageManager
        }'
      )
      echo "repository-context=$CONTEXT" >> $GITHUB_OUTPUT

  - name: Output results
    shell: bash
    run: |
      echo "Repository context: ${{ steps.repo-context.outputs.repository-context }}"
      echo "Configuration data: ${{ steps.config.outputs.config-data }}"
      echo "Environment variables: ${{ steps.set-env-vars.outputs.environment-variables }}"
      echo "Package manager: ${{ steps.detect-package-manager.outputs.package-manager }}"
      echo "Setup context and prerequisites completed successfully"
