name: 'Setup Context and Prerequisites'
description: 'Set up necessary context and prerequisites for the workflow'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'

outputs:
  repository-context:
    description: 'JSON object containing repository context'
  config-data:
    description: 'Parsed configuration data'
  environment-variables:
    description: 'Set environment variables'
  package-manager:
    description: 'Detected package manager'
  installation-status:
    description: 'Status of the installation process'
  changed_files:
    description: 'List of changed files in the current commit or PR'
  apps_configuration:
    description: 'Configuration for all apps in the repository'
  github_pages_urls:
    description: 'URLs of GitHub Pages for the repository'
  metrics_data:
    description: 'Metrics data from config.yml'
  security_checks:
    description: 'Security check configuration from config.yml'
  performance_monitoring:
    description: 'Performance monitoring configuration from config.yml'

runs:
  using: "composite"
  steps:
  - name: Install jq and yq
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y jq
      sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      sudo chmod +x /usr/bin/yq

  - name: Load and parse config.yml
    id: load_config
    shell: bash
    run: |
      CONFIG_CONTENT=$(cat "$GITHUB_WORKSPACE/.github/config.yml")
      if [ -z "$CONFIG_CONTENT" ]; then
        echo "Error: Failed to read config.yml"
        exit 1
      fi
      CONFIG_DATA=$(echo "$CONFIG_CONTENT" | yq eval -o=json -)
      if [ -z "$CONFIG_DATA" ]; then
        echo "Error: Failed to parse config.yml"
        exit 1
      fi
      echo "config-data=$CONFIG_DATA" >> $GITHUB_OUTPUT

  - name: Detect package manager
    id: detect_package_manager
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      PACKAGE_MANAGER=$(echo "$CONFIG_DATA" | jq -r '.packages.global_settings.ci_cd.package_manager // "unknown"')
      echo "package-manager=$PACKAGE_MANAGER" >> $GITHUB_OUTPUT

  - name: Fetch repository metadata
    id: fetch_repo_metadata
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: |
      REPO_METADATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/repos/$GITHUB_REPOSITORY")
      if [ -z "$REPO_METADATA" ]; then
        echo "Error: Failed to fetch repository metadata"
        exit 1
      fi
      echo "repo-metadata=$REPO_METADATA" >> $GITHUB_OUTPUT

  - name: Get changed files
    id: get_changed_files
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: |
      if [[ $GITHUB_REF == refs/pull/* ]]; then
        PR_NUMBER=${GITHUB_REF#refs/pull/}
        PR_NUMBER=${PR_NUMBER%/merge}
        CHANGED_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/files" \
          | jq -r '.[].filename')
      else
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
      fi
      echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

  - name: Set environment variables
    id: set_env_vars
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      {
        echo "REPO_NAME=${GITHUB_REPOSITORY}"
        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER}"
        echo "GITHUB_SHA=${GITHUB_SHA}"
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "REPO_TYPE=$(echo "$CONFIG_DATA" | jq -r '.repository.type // "monorepo"')"
        echo "MAIN_BRANCHES=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.main_branches // ["main", "develop"] | join(",")')"
        echo "BRANCH_PREFIXES=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.branch_prefixes // {} | to_entries | map("\(.key)=\(.value)") | join(",")')"
        echo "MERGE_STRATEGY=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.merge_strategy // empty')"
        echo "PROTECTED_BRANCHES=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.protected_branches // ["main", "develop"] | join(",")')"
        echo "PR_CREATION_WAIT_TIME=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.pr_creation_wait_time // 15')"
        echo "STALE_BRANCH_THRESHOLD=$(echo "$CONFIG_DATA" | jq -r '.repository.version_control.stale_branch_threshold // 30')"
      } >> $GITHUB_ENV
      echo "environment-variables=Environment variables set" >> $GITHUB_OUTPUT

  - name: Set repository context
    id: set_repo_context
    shell: bash
    run: |
      REPO_METADATA='${{ steps.fetch_repo_metadata.outputs.repo-metadata }}'
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      CHANGED_FILES='${{ steps.get_changed_files.outputs.changed_files }}'
      PACKAGE_MANAGER='${{ steps.detect_package_manager.outputs.package-manager }}'

      REPOSITORY_CONTEXT=$(jq -n \
        --argjson repoMetadata "$REPO_METADATA" \
        --argjson config "$CONFIG_DATA" \
        --arg branch "${GITHUB_REF#refs/heads/}" \
        --arg commit "$GITHUB_SHA" \
        --arg packageManager "$PACKAGE_MANAGER" \
        --argjson changedFiles "$(echo "$CHANGED_FILES" | jq -R -s 'split("\n")[:-1]')" \
        '{
          repoMetadata: $repoMetadata,
          config: $config,
          branch: $branch,
          commit: $commit,
          repoType: ($config.repository.type // "monorepo"),
          mainBranches: ($config.repository.version_control.main_branches // ["main", "develop"]),
          branchPrefixes: ($config.repository.version_control.branch_prefixes // {}),
          mergeStrategy: ($config.repository.version_control.merge_strategy // null),
          protectedBranches: ($config.repository.version_control.protected_branches // ["main", "develop"]),
          packageManager: $packageManager,
          changedFiles: $changedFiles,
          prCreationWaitTime: ($config.repository.version_control.pr_creation_wait_time // 15),
          staleBranchThreshold: ($config.repository.version_control.stale_branch_threshold // 30)
        }')
      echo "repository-context=$REPOSITORY_CONTEXT" >> $GITHUB_OUTPUT

  - name: Set apps configuration
    id: set_apps_config
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      APPS_CONFIG=$(echo "$CONFIG_DATA" | jq -r '.packages.package_specific // {}')
      echo "apps_configuration=$APPS_CONFIG" >> $GITHUB_OUTPUT

  - name: Set GitHub Pages URLs
    id: set_github_pages_urls
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      PAGES_URL=$(echo "$CONFIG_DATA" | jq -r '.packages.package_specific.web.ci_cd.deployment.production.url // empty')
      if [ -z "$PAGES_URL" ]; then
        PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}"
      fi
      echo "github_pages_urls=[\"$PAGES_URL\"]" >> $GITHUB_OUTPUT

  - name: Set metrics data
    id: set_metrics_data
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      METRICS_DATA=$(echo "$CONFIG_DATA" | jq -r '.metrics_generation // {}')
      echo "metrics_data=$METRICS_DATA" >> $GITHUB_OUTPUT

  - name: Set security checks configuration
    id: set_security_checks
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      SECURITY_CHECKS=$(echo "$CONFIG_DATA" | jq -r '.security_dependency_management // {}')
      echo "security_checks=$SECURITY_CHECKS" >> $GITHUB_OUTPUT

  - name: Set performance monitoring configuration
    id: set_performance_monitoring
    shell: bash
    run: |
      CONFIG_DATA='${{ steps.load_config.outputs.config-data }}'
      PERFORMANCE_MONITORING=$(echo "$CONFIG_DATA" | jq -r '.packages.global_settings.performance_monitoring // {}')
      echo "performance_monitoring=$PERFORMANCE_MONITORING" >> $GITHUB_OUTPUT

  - name: Completion message
    shell: bash
    run: |
      echo "Setup context and prerequisites completed successfully"
      if [ "${{ inputs.debug }}" = "true" ]; then
        echo "Debug: Repository Context"
        echo '${{ steps.set_repo_context.outputs.repository-context }}' | jq '.'
      fi
