name: 'Update Pull Request'
description: 'Updates a GitHub pull request with new information, including security checks and code analysis results'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'Pull request number to update'
    required: true
  pr-body:
    description: 'New body content for the pull request'
    required: true
  labels:
    description: 'Labels to apply to the pull request'
    required: false
  reviewers:
    description: 'Reviewers to assign to the pull request'
    required: false
  security-report:
    description: 'Security vulnerability report'
    required: false
  code-analysis:
    description: 'Code analysis results'
    required: false

runs:
  using: 'composite'
  steps:
  - name: Update Pull Request
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      PR_NUMBER: ${{ inputs.pr-number }}
      PR_BODY: ${{ inputs.pr-body }}
      LABELS: ${{ inputs.labels }}
      REVIEWERS: ${{ inputs.reviewers }}
      SECURITY_REPORT: ${{ inputs.security-report }}
      CODE_ANALYSIS: ${{ inputs.code-analysis }}
    run: |
      # Prepare the updated PR body
      UPDATED_BODY="$PR_BODY"

      if [ -n "$SECURITY_REPORT" ]; then
        UPDATED_BODY="$UPDATED_BODY

      ## Security Report
      $SECURITY_REPORT"
      fi

      if [ -n "$CODE_ANALYSIS" ]; then
        UPDATED_BODY="$UPDATED_BODY

      ## Code Analysis
      $CODE_ANALYSIS"
      fi

      # Update PR body
      gh pr edit $PR_NUMBER --body "$UPDATED_BODY"

      # Add labels if provided
      if [ -n "$LABELS" ]; then
        IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
        for label in "${LABEL_ARRAY[@]}"; do
          gh pr edit $PR_NUMBER --add-label "$label"
        done
      fi

      # Request reviewers if provided
      if [ -n "$REVIEWERS" ]; then
        IFS=',' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"
        gh pr edit $PR_NUMBER --add-reviewer "${REVIEWER_ARRAY[@]}"
      fi

      echo "Pull request #$PR_NUMBER updated successfully."
