name: 'Post PR Comment'
description: 'Posts informative comments on pull requests'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'Number of the pull request'
    required: true
  comment-content:
    description: 'Content of the comment to post'
    required: true

outputs:
  comment-status:
    description: 'Status of the comment posting operation'
  comment-url:
    description: 'URL of the posted comment'

runs:
  using: 'composite'
  steps:
  - name: Post comment
    id: post-comment
    shell: bash -l {0}
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      PR_NUMBER: ${{ inputs.pr-number }}
      COMMENT_CONTENT: ${{ inputs.comment-content }}
    run: |
      response=$(curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
        -d "{\"body\":\"$COMMENT_CONTENT\"}")

      comment_url=$(echo "$response" | jq -r '.html_url')

      if [ -n "$comment_url" ] && [ "$comment_url" != "null" ]; then
        echo "comment-status=success" >> $GITHUB_OUTPUT
        echo "comment-url=$comment_url" >> $GITHUB_OUTPUT
      else
        echo "comment-status=failure" >> $GITHUB_OUTPUT
        echo "Failed to post comment. Response: $response" >&2
      fi

  - name: Debug - Comment posting result
    shell: bash -l {0}
    run: |
      echo "Comment status: ${{ steps.post-comment.outputs.comment-status }}"
      echo "Comment URL: ${{ steps.post-comment.outputs.comment-url }}"
