name: 'Setup Repository Branch Rules'
description: 'Sets up branch protection rules for specified branches'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  branch-patterns:
    description: 'JSON string of branch patterns to protect'
    required: true
  protection-rules:
    description: 'JSON string of protection rules to apply'
    required: true

runs:
  using: "composite"
  steps:
  - name: Apply branch protection rules
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      BRANCH_PATTERNS: ${{ inputs.branch-patterns }}
      PROTECTION_RULES: ${{ inputs.protection-rules }}
    run: |
      branchPatterns=$(echo "$BRANCH_PATTERNS" | jq -r '.[]')
      for pattern in $branchPatterns; do
        echo "Applying protection rules to branch pattern: $pattern"

        response=$(curl -s -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/branches/$pattern/protection" \
          -d "$PROTECTION_RULES")

        if [[ $(echo "$response" | jq -r '.message') == "null" ]]; then
          echo "Successfully applied protection rules to $pattern"
        else
          echo "Error applying protection rules to $pattern: $(echo "$response" | jq -r '.message')"
        fi
      done

  - name: Generate summary
    id: generate-summary
    shell: bash
    run: |
      echo "Branch protection rules applied to patterns: ${{ inputs.branch-patterns }}" >> $GITHUB_OUTPUT
