name: Automated Testing Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Packages
        id: get-packages
        run: |
          packages=$(echo '${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific }}' | jq -r 'keys | @json')
          echo "packages=$packages" >> $GITHUB_OUTPUT

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.setup.outputs.packages) }}
      fail-fast: false

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        id: install-dependencies
        uses: ./.github/actions/install-dependencies
        with:
          package-manager: ${{ fromJson(steps.setup-context.outputs.config-data).packages.global_settings.package_manager }}
          working-directory: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].path }}

      - name: Run Unit Tests
        id: run-unit-tests
        uses: ./.github/actions/run-tests
        with:
          test-type: 'unit'
          test-command: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].ci_cd.commands.test }}
          working-directory: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].path }}

      - name: Run Integration Tests
        id: run-integration-tests
        uses: ./.github/actions/run-tests
        with:
          test-type: 'integration'
          test-command: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].ci_cd.commands.test }}
          working-directory: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].path }}

      - name: Run E2E Tests
        id: run-e2e-tests
        uses: ./.github/actions/run-tests
        with:
          test-type: 'e2e'
          test-command: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].ci_cd.commands.test }}
          working-directory: ${{ fromJson(steps.setup-context.outputs.config-data).packages.package_specific[matrix.package].path }}

      - name: Generate Test Report
        id: generate-test-report
        uses: ./.github/actions/generate-test-report
        with:
          unit-test-results: ${{ steps.run-unit-tests.outputs.test-results }}
          integration-test-results: ${{ steps.run-integration-tests.outputs.test-results }}
          e2e-test-results: ${{ steps.run-e2e-tests.outputs.test-results }}
          package-name: ${{ matrix.package }}

      - name: Upload Test Results
        id: upload-test-results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.package }}
          path: test-report-${{ matrix.package }}.json

      - name: Notify on Test Failure
        id: notify-failure
        if: failure()
        uses: ./.github/actions/send-notification
        with:
          notification-type: "ci_cd_status"
          notification-data: |
            {
              "workflow": "Automated Testing",
              "package": "${{ matrix.package }}",
              "status": "failed",
              "details": "Check the workflow run for more information."
            }
          config-path: '.github/config.yml'