name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Get Packages
        id: get-packages
        run: |
          packages=$(echo '${{ steps.setup-context.outputs.apps_configuration }}' | jq -r 'keys | @json')
          echo "packages=$packages" >> $GITHUB_OUTPUT

  ci-cd:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.setup.outputs.packages) }}
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Validate Configuration
        id: validate-config
        uses: ./.github/actions/validate-config
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Install Dependencies
        id: install-dependencies
        uses: ./.github/actions/install-dependencies
        with:
          package-manager: ${{ steps.setup-context.outputs.repository-context.packageManager }}
          cache-key: ${{ runner.os }}-${{ matrix.package }}-${{ hashFiles(format('{0}/package-lock.json', steps.setup-context.outputs.apps_configuration[matrix.package].path)) }}
          working-directory: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].path }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Run Linting
        id: run-linting
        uses: ./.github/actions/run-linting
        with:
          working-directory: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].path }}
          lint-command: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.commands.lint }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Run Tests
        id: run-tests
        uses: ./.github/actions/run-tests
        with:
          working-directory: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].path }}
          test-command: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.commands.test }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Upload Code Coverage
        id: upload-coverage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-code-coverage-report
          path: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].path }}/coverage
          if-no-files-found: warn
          retention-days: 14

      - name: Build Application
        id: build-app
        uses: ./.github/actions/build-app
        with:
          build-command: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.commands.build }}
          working-directory: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].path }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Deploy Application
        id: deploy-app
        if: github.event_name == 'push'
        uses: ./.github/actions/deploy-app
        with:
          package-name: ${{ matrix.package }}
          artifacts-path: ${{ steps.build-app.outputs.artifacts-path }}
          deployment-type: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.deployment.type }}
          deployment-config: ${{ toJson(steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.deployment.config) }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Run Post-Deployment Tests
        id: post-deployment-tests
        if: github.event_name == 'push' && steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.post_deployment_tests.enabled == 'true'
        uses: ./.github/actions/run-post-deployment-tests
        with:
          app-url: ${{ steps.deploy-app.outputs.deployed-url }}
          test-suite: ${{ steps.setup-context.outputs.apps_configuration[matrix.package].ci_cd.post_deployment_tests.url }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Send Notifications
        id: send-notifications
        uses: ./.github/actions/send-notification
        with:
          notification-type: 'ci_cd_status'
          notification-data: |
            {
              "repository": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "package": "${{ matrix.package }}",
              "status": "${{ job.status }}",
              "run_id": "${{ github.run_id }}",
              "run_number": "${{ github.run_number }}"
            }
          github-token: ${{ env.GH_TOKEN }}

      - name: Create Issue on Failure
        id: create-issue-on-failure
        if: failure()
        uses: ./.github/actions/create-issue
        with:
          github-token: ${{ env.GH_TOKEN }}
          issue-title: "CI/CD Workflow Failure for ${{ matrix.package }}"
          issue-body: "The CI/CD workflow failed for package ${{ matrix.package }}. Please check the logs for more details."
          labels: "bug,ci-cd,${{ matrix.package }}"
