name: Dependency Management Workflow

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  dependency-management:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Context
        uses: ./.github/actions/setup-context-and-prerequisites
        id: setup-context
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Check for Updates
        id: check-updates
        uses: ./.github/actions/check-dependency-updates
        with:
          package-manager-type: ${{ steps.setup-context.outputs.package-manager }}
          current-dependencies: ${{ steps.setup-context.outputs.current-dependencies }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Run Security Vulnerability Scan
        id: security-scan
        uses: ./.github/actions/security-vulnerability-scan
        with:
          current-dependencies: ${{ steps.setup-context.outputs.current-dependencies }}
          vulnerability-databases: ${{ steps.setup-context.outputs.vulnerability-databases }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Create Update PRs
        id: create-dependency-update-prs
        uses: ./.github/actions/create-dependency-update-prs
        with:
          update-report: ${{ steps.check-updates.outputs.update-report }}
          vulnerability-report: ${{ steps.security-scan.outputs.vulnerability-report }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Run Tests on Update PRs
        id: run-tests
        uses: ./.github/actions/run-tests
        with:
          pr-changes: ${{ steps.create-dependency-update-prs.outputs.created-prs }}
          test-command: ${{ steps.setup-context.outputs.test-command }}
          coverage-command: ${{ steps.setup-context.outputs.coverage-command }}
          coverage-threshold: ${{ steps.setup-context.outputs.coverage-threshold }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Update PR Descriptions
        uses: ./.github/actions/create-or-update-pr
        with:
          pr-numbers: ${{ steps.create-dependency-update-prs.outputs.created-prs }}
          pr-body: |
            Test Results: ${{ steps.run-tests.outputs.test-status }}
            Coverage Report: ${{ steps.run-tests.outputs.coverage-report }}
            Update Details: ${{ steps.check-updates.outputs.update-report }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Auto-merge Minor/Patch Updates
        uses: ./.github/actions/auto-merge-updates
        with:
          pr-details: ${{ steps.create-dependency-update-prs.outputs.created-prs }}
          auto-merge-settings: ${{ steps.setup-context.outputs.auto-merge-settings }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Notify Team
        if: ${{ steps.setup-context.outputs.notify-team == 'true' }}
        uses: ./.github/actions/send-notification
        with:
          notification-type: "dependency_updates"
          notification-data: |
            {
              "created-prs": ${{ steps.create-dependency-update-prs.outputs.created-prs }},
              "security-vulnerabilities": ${{ steps.security-scan.outputs.vulnerability-report }}
            }
          github-token: ${{ env.GH_TOKEN }}
