name: Issue Management Workflow

on:
  issues:
    types: [opened, edited, labeled]
  schedule:
    - cron: '0 1 * * *'  # Daily at 01:00 UTC

permissions: {}

jobs:
  issue-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Context
        uses: ./.github/actions/setup-context-and-prerequisites
        id: setup-context
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Label
        uses: ./.github/actions/auto-label
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          labeling-rules: ${{ steps.setup-context.outputs.auto-label-rules }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Assign
        uses: ./.github/actions/auto-assign
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          assignment-rules: ${{ steps.setup-context.outputs.auto-assign-rules }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Auto Response
        uses: ./.github/actions/ai-generate-content
        id: generate-auto-response
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "issue_response"
          context-data: |
            {
              "issue-title": "${{ github.event.issue.title }}",
              "issue-body": "${{ github.event.issue.body }}"
            }
          template-path: ${{ steps.setup-context.outputs.auto-response-template-path }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Issue
        uses: ./.github/actions/update-issue
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-body: ${{ steps.generate-auto-response.outputs.generated-content }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Related Project Card
        uses: ./.github/actions/create-project-card
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          project-board-id: ${{ steps.setup-context.outputs.default-project-board }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Related Issues/PRs
        uses: ./.github/actions/link-related-items
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prioritize Issue
        uses: ./.github/actions/prioritize-issue
        with:
          issue-number: ${{ github.event.issue.number }}
          prioritization-rules: ${{ steps.setup-context.outputs.prioritization-rules }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Milestone
        uses: ./.github/actions/set-milestone
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          milestone-rules: ${{ steps.setup-context.outputs.milestone-rules }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Notifications
        uses: ./.github/actions/send-notification
        with:
          notification-type: "issue_update"
          notification-data: |
            {
              "issue-url": "${{ github.event.issue.html_url }}",
              "issue-title": "${{ github.event.issue.title }}",
              "action": "${{ github.event.action }}"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Track SLA
        uses: ./.github/actions/track-sla
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          sla-timeframe: ${{ steps.setup-context.outputs.sla-timeframe }}
          warning-threshold: ${{ steps.setup-context.outputs.sla-warning-threshold }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Stale Issues
        if: github.event_name == 'schedule'
        uses: ./.github/actions/close-stale-issues
        with:
          stale-threshold: ${{ steps.setup-context.outputs.stale-issue-threshold }}
          exempt-labels: ${{ steps.setup-context.outputs.stale-exempt-labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
