name: Issue Management Workflow

on:
  issues:
    types: [opened, edited, labeled]
  schedule:
    - cron: '0 1 * * *'  # Daily at 01:00 UTC

jobs:
  issue-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Context
        uses: ./.github/actions/setup-context-and-prerequisites
        id: setup-context
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Auto Label
        uses: ./.github/actions/auto-label
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          labeling-rules: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.auto_label.rules }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Auto Assign
        uses: ./.github/actions/auto-assign
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          assignment-rules: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.auto_assign.expertise_map }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Generate Auto Response
        uses: ./.github/actions/ai-generate-content
        id: generate-auto-response
        with:
          content-type: "issue_response"
          context-data: |
            {
              "issue-title": "${{ github.event.issue.title }}",
              "issue-body": "${{ github.event.issue.body }}"
            }
          template-path: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.auto_response.template_path }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Update Issue
        uses: ./.github/actions/update-issue
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-body: ${{ steps.generate-auto-response.outputs.generated-content }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Create Related Project Card
        uses: ./.github/actions/create-project-card
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          project-board-id: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.default_project_board }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Link Related Issues/PRs
        uses: ./.github/actions/link-related-items
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Prioritize Issue
        uses: ./.github/actions/prioritize-issue
        with:
          issue-number: ${{ github.event.issue.number }}
          prioritization-rules: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.prioritization.rules }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Set Milestone
        uses: ./.github/actions/set-milestone
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          milestone-rules: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.milestone_setting }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Send Notifications
        uses: ./.github/actions/send-notification
        with:
          notification-type: "issue_update"
          notification-data: |
            {
              "issue-url": "${{ github.event.issue.html_url }}",
              "issue-title": "${{ github.event.issue.title }}",
              "action": "${{ github.event.action }}"
            }
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Track SLA
        uses: ./.github/actions/track-sla
        with:
          item-type: 'issue'
          item-number: ${{ github.event.issue.number }}
          sla-timeframe: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.sla_tracking.timeframe }}
          warning-threshold: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.sla_tracking.warning_threshold }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Close Stale Issues
        if: github.event_name == 'schedule'
        uses: ./.github/actions/close-stale-issues
        with:
          stale-threshold: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.stale_issue_threshold }}
          exempt-labels: ${{ fromJson(steps.setup-context.outputs.config-data).issue_management.stale_exempt_labels }}
          github-token: ${{ secrets.GH_TOKEN }}
