name: Metrics Generation Workflow

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at 00:00 UTC
  release:
    types: [created]
  workflow_dispatch:

permissions: {}

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ env.GH_TOKEN }}

      - name: Generate Metrics
        id: generate-metrics
        uses: ./.github/actions/generate-metrics
        with:
          repository-context: ${{ steps.setup-context.outputs.repository-context }}
          metrics-to-collect: ${{ steps.setup-context.outputs.metrics-to-collect }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Generate Metrics Report
        id: generate-metrics-report
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "metrics_analysis"
          context-data: |
            {
              "metrics-data": ${{ steps.generate-metrics.outputs.metrics-data }},
              "top-contributors": ${{ steps.generate-metrics.outputs.top-contributors }},
              "improvement-areas": ${{ steps.generate-metrics.outputs.improvement-areas }}
            }
          template-path: .github/templates/performance_metrics_report_template.md

      - name: Create Discussion Post
        id: create-discussion-post
        if: ${{ steps.setup-context.outputs.create-discussion-post == 'true' }}
        uses: ./.github/actions/create-discussion-post
        with:
          discussion-category: ${{ steps.setup-context.outputs.discussion-category }}
          discussion-title: ${{ steps.setup-context.outputs.discussion-title }}
          discussion-content: ${{ steps.generate-metrics-report.outputs.generated-content }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Generate Contributor Engagement Content
        id: generate-contributor-engagement-content
        if: ${{ steps.setup-context.outputs.contributor-engagement-enabled == 'true' }}
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "contributor_engagement"
          context-data: |
            {
              "top-contributors": ${{ steps.generate-metrics.outputs.top-contributors }},
              "top-contributors-count": ${{ steps.setup-context.outputs.top-contributors-count }}
            }
          github-token: ${{ env.GH_TOKEN }}

      - name: Send Contributor Engagement Messages
        id: send-contributor-engagement-messages
        if: ${{ steps.setup-context.outputs.contributor-engagement-enabled == 'true' }}
        uses: ./.github/actions/send-notification
        with:
          notification-type: "contributor_engagement"
          notification-data: ${{ steps.generate-contributor-engagement-content.outputs.generated-content }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Send Notification
        id: send-notification
        if: ${{ steps.setup-context.outputs.send-notification == 'true' }}
        uses: ./.github/actions/send-notification
        with:
          notification-type: ${{ steps.setup-context.outputs.notification-type }}
          notification-data: |
            {
              "metrics-report-url": "${{ steps.create-discussion-post.outputs.created-discussion-url }}"
            }
          github-token: ${{ env.GH_TOKEN }}

      - name: Send Webhook
        id: send-webhook
        if: ${{ steps.setup-context.outputs.send-webhook == 'true' }}
        uses: ./.github/actions/send-webhook
        with:
          webhook-type: ${{ steps.setup-context.outputs.webhook-type }}
          webhook-data: |
            {
              "metrics-data": ${{ steps.generate-metrics.outputs.metrics-data }},
              "metrics-report": ${{ steps.generate-metrics-report.outputs.generated-content }}
            }
          github-token: ${{ env.GH_TOKEN }}

      - name: Generate Improvement Suggestions
        id: generate-improvement-suggestions
        if: ${{ steps.setup-context.outputs.improvement-suggestions-enabled == 'true' }}
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "improvement_suggestions"
          context-data: |
            {
              "improvement-needs": ${{ steps.generate-metrics.outputs.improvement-areas }}
            }
          github-token: ${{ env.GH_TOKEN }}

      - name: Create Improvement Issues
        id: create-improvement-issues
        if: ${{ steps.setup-context.outputs.create-improvement-issues == 'true' }}
        uses: ./.github/actions/create-issues
        with:
          issues-data: ${{ steps.generate-improvement-suggestions.outputs.generated-content }}
          github-token: ${{ env.GH_TOKEN }}