name: Performance and Availability Monitoring Workflow

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Availability
        id: check-availability
        uses: ./.github/actions/check-site-availability
        with:
          urls: ${{ steps.setup-context.outputs.github_pages_urls }}

      - name: Measure Performance
        id: measure-performance
        uses: ./.github/actions/measure-site-performance
        with:
          urls: ${{ steps.setup-context.outputs.github_pages_urls }}

      - name: Analyze Results
        id: analyze-results
        uses: ./.github/actions/analyze-performance-results
        with:
          availability-status: ${{ steps.check-availability.outputs.availability_status }}
          performance-metrics: ${{ steps.measure-performance.outputs.performance_metrics }}

      - name: Create Issues (if needed)
        id: create-issues
        if: steps.analyze-results.outputs.issue_type != ''
        uses: ./.github/actions/create-issue
        with:
          issue-type: ${{ steps.analyze-results.outputs.issue_type }}
          issue-details: ${{ steps.analyze-results.outputs.issue_details }}
          issue-template: .github/templates/issue_auto_generated_template.md

      - name: Send Notifications
        id: send-notifications
        uses: ./.github/actions/send-notification
        with:
          notification-type: "performance_availability"
          notification-data: |
            {
              "analysis-report": ${{ steps.analyze-results.outputs.analysis_report }},
              "issue-url": "${{ steps.create-issues.outputs.issue_url }}"
            }

      - name: Send Webhook
        id: send-webhook
        uses: ./.github/actions/send-webhook
        with:
          webhook-type: "performance_availability_data"
          webhook-data: |
            {
              "performance-data": ${{ steps.measure-performance.outputs.performance_metrics }},
              "availability-data": ${{ steps.check-availability.outputs.availability_status }}
            }

      - name: Create Monitoring Failure Issue
        id: create-monitoring-failure-issue
        if: failure()
        uses: ./.github/actions/create-issue
        with:
          issue-title: "Performance Monitoring Failed"
          issue-body: "The performance and availability monitoring workflow encountered an error. Manual check required."
          labels: '["high-priority", "monitoring-error"]'
