name: Project Publish

on:
  push:
    branches: ["main", "develop", "feature/*", "release/*", "hotfix/*", "ci/*", "chore/*"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check_prerequisites:
    runs-on: ubuntu-latest
    outputs:
      groq_api_key_valid: ${{ steps.validate_groq_api_key.outputs.is_valid }}
    steps:
      - name: Validate GROQ API Key
        id: validate_groq_api_key
        run: |
          if [ -n "${{ secrets.GROQ_API_KEY }}" ]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
            echo "GROQ_API_KEY is set and not empty"
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
            echo "Error: GROQ_API_KEY is not set or empty"
          fi

  setup:
    needs: check_prerequisites
    if: needs.check_prerequisites.outputs.groq_api_key_valid == 'true'
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Generate Cache Key
        id: cache-key
        run: echo "key=${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

      - name: Cache Turbo dependencies
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  check_project_changes:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Changes
        id: check
        run: |
          echo "changes=[\"all\"]" >> $GITHUB_OUTPUT
          echo "Detected changes in all projects"

  build_packages:
    runs-on: ubuntu-latest
    needs: [setup, check_project_changes]
    if: contains(fromJson(needs.check_project_changes.outputs.changes), 'all') || contains(fromJson(needs.check_project_changes.outputs.changes), 'packages')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-and-deps
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

      - name: Build Packages
        run: yarn turbo run build --filter=./packages/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages-build
          path: ./packages

  build_web:
    runs-on: ubuntu-latest
    needs: [setup, check_project_changes]
    if: contains(fromJson(needs.check_project_changes.outputs.changes), 'all') || contains(fromJson(needs.check_project_changes.outputs.changes), 'web')
    env:
      NEXT_PUBLIC_PLUNK_API_KEY: ${{ secrets.NEXT_PUBLIC_PLUNK_API_KEY }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-and-deps
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

      - name: Build Web
        run: yarn turbo run build --filter=web...

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web/out

  build_chrome_extension:
    runs-on: ubuntu-latest
    needs: [setup, check_project_changes]
    if: contains(fromJson(needs.check_project_changes.outputs.changes), 'all') || contains(fromJson(needs.check_project_changes.outputs.changes), 'chrome-extension')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-and-deps
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

      - name: Build Chrome Extension
        run: yarn turbo run build --filter=chrome-extension...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-build
          path: ./apps/chrome-extension/dist

  prepare_release:
    runs-on: ubuntu-latest
    needs: [build_packages, build_web, build_chrome_extension]
    if: github.ref == 'refs/heads/main'
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      has_extension_changes: ${{ steps.check_extension_changes.outputs.has_changes }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Extension Changes
        id: check_extension_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^apps/chrome-extension/' && echo "has_changes=true" >> $GITHUB_OUTPUT || echo "has_changes=false" >> $GITHUB_OUTPUT

      - name: Determine Version
        id: version
        run: |
          current_version=$(jq -r '.version' package.json)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Prepare Changelog Request Data
        run: |
          commits_json=$(echo '${{ toJson(github.event.commits) }}' | jq -c '.')
          request_data=$(jq -n \
            --arg model "llama-3.1-70b-versatile" \
            --arg system_content "You are an AI assistant tasked with creating detailed and user-friendly changelogs. Respond in JSON format with a key 'changelog'." \
            --arg user_content "Create a detailed and user-friendly changelog for the following commits: $commits_json" \
            '{
              model: $model,
              messages: [
                {role: "system", content: $system_content},
                {role: "user", content: $user_content}
              ],
              temperature: 0.3,
              response_format: {type: "json_object"}
            }')
          echo "REQUEST_DATA<<EOF" >> $GITHUB_ENV
          echo "$request_data" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug Changelog Request Data
        run: |
          echo "Request Data:"
          echo "$REQUEST_DATA" | jq .

      - name: Generate Changelog
        id: changelog
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.groq.com/openai/v1/chat/completions'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.GROQ_API_KEY }}", "Content-Type": "application/json"}'
          data: ${{ env.REQUEST_DATA }}

      - name: Parse Changelog
        run: |
          changelog_data='${{ steps.changelog.outputs.response }}'
          changelog=$(echo "$changelog_data" | jq -r '.choices[0].message.content | fromjson | .changelog // empty')
          if [ -z "$changelog" ]; then
            echo "Error: Generated changelog is null or empty. Exiting."
            exit 1
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  deploy_web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [prepare_release, build_web]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update package.json for Web
        run: |
          jq '.version = "${{ needs.prepare_release.outputs.new_version }}"' apps/web/package.json > apps/web/package.json.tmp
          mv apps/web/package.json.tmp apps/web/package.json

      - name: Commit Web Version Update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add apps/web/package.json
          git commit -m "chore(web): bump version to ${{ needs.prepare_release.outputs.new_version }}"
          git push

  release_extension:
    needs: prepare_release
    runs-on: ubuntu-latest
    if: ${{ needs.prepare_release.outputs.has_extension_changes == 'true' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Chrome Extension Artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-build
          path: releases

      - name: Create GitHub Release for Extension
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare_release.outputs.new_version }}-extension
          name: Chrome Extension Release v${{ needs.prepare_release.outputs.new_version }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
          files: releases/STC_Beta_*.zip
          token: ${{ github.token }}

      - name: Update package.json for Extension
        run: |
          jq '.version = "${{ needs.prepare_release.outputs.new_version }}"' apps/chrome-extension/package.json > apps/chrome-extension/package.json.tmp
          mv apps/chrome-extension/package.json.tmp apps/chrome-extension/package.json

      - name: Commit Extension Version Update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add apps/chrome-extension/package.json
          git commit -m "chore(extension): bump version to ${{ needs.prepare_release.outputs.new_version }}"
          git push