name: Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  prepare_release:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      should_release: ${{ steps.check_changes.outputs.should_release }}
      new_version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Relevant Changes
        id: check_changes
        run: |
          changes=$(git diff --name-only ${{ github.event.workflow_run.head_sha }} ${{ github.sha }})
          if echo "$changes" | grep -qE "^(apps/web|apps/chrome-extension|packages)/"; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine Version
        id: version
        if: steps.check_changes.outputs.should_release == 'true'
        run: |
          current_version=$(jq -r '.version' package.json)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Validate GROQ API Key
        run: |
          if [ -z "${{ secrets.GROQ_API_KEY }}" ]; then
            echo "Error: GROQ_API_KEY is not set or empty"
            exit 1
          fi
          echo "GROQ_API_KEY is set and not empty"

      - name: Generate Release Notes with AI
        id: changelog
        if: steps.check_changes.outputs.should_release == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.groq.com/openai/v1/chat/completions'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.GROQ_API_KEY }}", "Content-Type": "application/json"}'
          data: |
            {
              "model": "llama-3.1-70b-versatile",
              "messages": [
                {"role": "system", "content": "You are an AI assistant tasked with creating detailed and user-friendly changelogs. Respond in JSON format with a key 'changelog'."},
                {"role": "user", "content": "Create a detailed and user-friendly changelog for the following commits: ${{ github.event.commits }}"}
              ],
              "temperature": 0.3,
              "response_format": {"type": "json_object"}
            }

      - name: Parse Changelog
        if: steps.check_changes.outputs.should_release == 'true'
        run: |
          changelog_data='${{ steps.changelog.outputs.response }}'
          changelog=$(echo "$changelog_data" | jq -r '.choices[0].message.content | fromjson | .changelog // empty')

          if [ -z "$changelog" ]; then
            echo "Error: Generated changelog is null or empty. Exiting."
            exit 1
          fi

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  release:
    needs: prepare_release
    if: needs.prepare_release.outputs.should_release == 'true'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Update package.json
        run: |
          jq '.version = "${{ needs.prepare_release.outputs.new_version }}"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Commit Version Update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ needs.prepare_release.outputs.new_version }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare_release.outputs.new_version }}
          name: Release v${{ needs.prepare_release.outputs.new_version }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
          token: ${{ github.token }}

      - name: Download Chrome Extension Artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension
          path: releases
          run-id: ${{ github.event.workflow_run.id }}

      - name: Attach Chrome Extension to Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/STC_Beta_*.zip
          tag_name: v${{ needs.prepare_release.outputs.new_version }}
          token: ${{ github.token }}