name: Repository Setup Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  check-repository-setup:
    runs-on: ubuntu-latest
    outputs:
      is-configured: ${{ steps.check-config.outputs.is-configured }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check repository configuration
        id: check-config
        run: |
          if [ -f ".github/enabled" ]; then
            echo "is-configured=true" >> $GITHUB_OUTPUT
          else
            echo "is-configured=false" >> $GITHUB_OUTPUT
          fi

  repository-setup:
    needs: check-repository-setup
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Context and Prerequisites
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: 'true'

      - name: Create Git Flow Branches
        uses: ./.github/actions/create-or-update-branch
        with:
          branch-name: ${{ steps.setup-context.outputs.main_branch }}
          base-branch: 'main'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Debug Branch Creation
        if: failure()
        run: |
          echo "Debug: An error occurred during branch creation/update"
          echo "operation-status=failed" >> $GITHUB_OUTPUT
        
      - name: Generate Content
        id: generate-content
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "repository_docs"
          context-data: ${{ steps.setup-context.outputs.repository-context }}
          template-path: .github/templates/repository_setup_template.md
          tone: ${{ steps.setup-context.outputs.documentation_tone }}
          max-length: ${{ steps.setup-context.outputs.documentation_max_length }}

      - name: Setup Branch Protection Rules
        uses: ./.github/actions/apply-branch-protection
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-patterns: ${{ steps.setup-context.outputs.protected_branches }}
          protection-rules: ${{ steps.setup-context.outputs.branch_protection_rules }}

      - name: Create Wiki Pages
        uses: ./.github/actions/create-wiki-page
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          page-name: "Git Flow Process"
          page-content: ${{ steps.generate-content.outputs.generated-content }}

      - name: Create Discussion Posts
        uses: ./.github/actions/create-discussion-post
        with:
          discussion-title: "Welcome to the Repository"
          discussion-content: ${{ steps.generate-content.outputs.generated-content }}
          category: ${{ steps.setup-context.outputs.initial_discussion_category }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Issue Labels
        uses: ./.github/actions/setup-issue-labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.setup-context.outputs.initial_labels }}

      - name: Setup Project Board
        uses: ./.github/actions/setup-project-board
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          columns: ${{ steps.setup-context.outputs.project_board_columns }}

      - name: Setup Repository Settings
        uses: ./.github/actions/setup-repository-settings
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          has-wiki: ${{ steps.setup-context.outputs.has_wiki }}
          has-issues: ${{ steps.setup-context.outputs.has_issues }}
          has-projects: ${{ steps.setup-context.outputs.has_projects }}
          allow-squash-merge: ${{ steps.setup-context.outputs.allow_squash_merge }}
          allow-merge-commit: ${{ steps.setup-context.outputs.allow_merge_commit }}
          allow-rebase-merge: ${{ steps.setup-context.outputs.allow_rebase_merge }}
          delete-branch-on-merge: ${{ steps.setup-context.outputs.delete_branch_on_merge }}

      - name: Setup Dependabot
        uses: ./.github/actions/setup-dependabot
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ecosystems: ${{ steps.setup-context.outputs.dependabot_ecosystems }}
          config: ${{ steps.setup-context.outputs.dependabot_config }}

      - name: Setup CODEOWNERS
        uses: ./.github/actions/setup-codeowners
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository-admins: ${{ steps.setup-context.outputs.default_code_owners }}

      - name: Commit Changes
        uses: ./.github/actions/commit-changes
        with:
          commit-message: "chore: initial repository setup"
          files: ${{ steps.setup-context.outputs.initial_files }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: ./.github/actions/create-or-update-branch
        with:
          branch-name: 'initial-setup'
          base-branch: 'main'
          commit-changes: |
            chore: initial repository setup
            
            - feat: add initial repository files and configurations
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Notification
        uses: ./.github/actions/send-notification
        with:
          notification-type: "setup_completion"
          notification-data: |
            {
              "setup-details": ${{ toJson(steps) }}
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark repository as configured
        run: |
          echo '{"configured": true}' > .github/enabled
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/enabled
          git commit -m "chore: mark repository as configured"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
