name: Repository Setup Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  check-repository-setup:
    runs-on: ubuntu-latest
    outputs:
      is-configured: ${{ steps.check-config.outputs.is-configured }}
      setup-context: ${{ steps.setup-context.outputs.context }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check repository configuration
        id: check-config
        run: |
          if [ -f ".github/enabled" ]; then
            echo "is-configured=true" >> $GITHUB_OUTPUT
          else
            echo "is-configured=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Context and Prerequisites
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  setup-branches:
    needs: check-repository-setup
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Setup Repository Branches
        uses: ./.github/actions/setup-repository-branches
        with:
          branches: ${{ toJson(env.SETUP_CONTEXT.mainBranches) }}
          base-branch: 'main'
          github-token: ${{ env.GH_TOKEN }}
        continue-on-error: true

      - name: Debug Branch Creation
        if: failure()
        run: |
          echo "Debug: An error occurred during branch creation/update"
          echo "operation-status=failed" >> $GITHUB_OUTPUT

  generate-content:
    needs: check-repository-setup
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Wiki Content
        id: generate-wiki-content
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "wiki_page"
          context-data: ${{ toJson(env.SETUP_CONTEXT) }}
          template-path: .github/templates/wiki_template.md
          tone: ${{ env.SETUP_CONTEXT.config.repository.documentation_tone }}
          max-length: ${{ env.SETUP_CONTEXT.config.repository.documentation_max_length }}

      - name: Generate Discussion Content
        id: generate-discussion-content
        uses: ./.github/actions/ai-generate-content
        with:
          ai-api-key: ${{ secrets.GOOGLE_AI_API_KEY }}
          content-type: "discussion_post"
          context-data: ${{ toJson(env.SETUP_CONTEXT) }}
          template-path: .github/templates/discussion_template.md
          tone: ${{ env.SETUP_CONTEXT.config.repository.documentation_tone }}
          max-length: ${{ env.SETUP_CONTEXT.config.repository.documentation_max_length }}

  setup-repository-rules:
    needs: [check-repository-setup, setup-branches]
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Branch Protection Rules
        uses: ./.github/actions/setup-repository-branch-rules
        with:
          github-token: ${{ env.GH_TOKEN }}
          branch-patterns: ${{ toJson(env.SETUP_CONTEXT.protectedBranches) }}
          protection-rules: ${{ toJson(env.SETUP_CONTEXT.config.repository.version_control.branch_protection_rules) }}

  create-wiki-and-discussions:
    needs: [check-repository-setup, generate-content]
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Wiki Pages
        uses: ./.github/actions/create-wiki-page
        with:
          github-token: ${{ env.GH_TOKEN }}
          page-name: "Git Flow Process"
          page-content: ${{ needs.generate-content.outputs.generate-wiki-content }}

      - name: Create Discussion Posts
        uses: ./.github/actions/create-discussion-post
        with:
          discussion-title: "Welcome to the Repository"
          discussion-content: ${{ needs.generate-content.outputs.generate-discussion-content }}
          category: ${{ env.SETUP_CONTEXT.config.repository.initial_discussion_category }}
          github-token: ${{ env.GH_TOKEN }}

  setup-repository-features:
    needs: check-repository-setup
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Issue Labels
        uses: ./.github/actions/setup-issue-labels
        with:
          github-token: ${{ env.GH_TOKEN }}
          labels: ${{ toJson(env.SETUP_CONTEXT.config.issue_management.auto_label.rules) }}

      - name: Setup Project Board
        uses: ./.github/actions/setup-project-board
        with:
          github-token: ${{ env.GH_TOKEN }}
          columns: ${{ toJson(env.SETUP_CONTEXT.config.repository.project_board_columns) }}

      - name: Setup Repository Settings
        uses: ./.github/actions/setup-repository-settings
        with:
          github-token: ${{ env.GH_TOKEN }}
          has-wiki: ${{ env.SETUP_CONTEXT.config.repository.has_wiki }}
          has-issues: ${{ env.SETUP_CONTEXT.config.repository.has_issues }}
          has-projects: ${{ env.SETUP_CONTEXT.config.repository.has_projects }}
          allow-squash-merge: ${{ env.SETUP_CONTEXT.config.repository.version_control.merge_strategy.allow_squash_merge }}
          allow-merge-commit: ${{ env.SETUP_CONTEXT.config.repository.version_control.merge_strategy.allow_merge_commit }}
          allow-rebase-merge: ${{ env.SETUP_CONTEXT.config.repository.version_control.merge_strategy.allow_rebase_merge }}
          delete-branch-on-merge: ${{ env.SETUP_CONTEXT.config.repository.version_control.delete_branch_on_merge }}

  setup-security-features:
    needs: check-repository-setup
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dependabot
        uses: ./.github/actions/setup-dependabot
        with:
          github-token: ${{ env.GH_TOKEN }}
          ecosystems: ${{ toJson(env.SETUP_CONTEXT.config.security_dependency_management.security_check.tools) }}
          schedule: ${{ env.SETUP_CONTEXT.config.security_dependency_management.schedule }}

      - name: Setup CODEOWNERS
        uses: ./.github/actions/setup-codeowners
        with:
          github-token: ${{ env.GH_TOKEN }}
          repository-admins: ${{ toJson(env.SETUP_CONTEXT.config.repository.default_code_owners) }}

  finalize-setup:
    needs: [setup-branches, setup-repository-rules, create-wiki-and-discussions, setup-repository-features, setup-security-features]
    if: needs.check-repository-setup.outputs.is-configured == 'false'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SETUP_CONTEXT: ${{ fromJson(needs.check-repository-setup.outputs.setup-context) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Commit Changes
        uses: ./.github/actions/commit-changes
        with:
          commit-message: "chore: initial repository setup"
          files: ${{ toJson(env.SETUP_CONTEXT.config.repository.initial_files) }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Create Pull Request
        uses: ./.github/actions/create-or-update-branch
        with:
          branch-name: 'initial-setup'
          base-branch: 'main'
          commit-changes: |
            chore: initial repository setup
            
            - feat: add initial repository files and configurations
          github-token: ${{ env.GH_TOKEN }}

      - name: Send Notification
        uses: ./.github/actions/send-notification
        with:
          notification-type: "setup_completion"
          notification-data: ${{ toJson(fromJson(needs.check-repository-setup.outputs.setup-context)) }}
          github-token: ${{ env.GH_TOKEN }}

      - name: Mark repository as configured
        run: |
          echo '{"configured": true}' > .github/enabled
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/enabled
          git commit -m "chore: mark repository as configured"
          git push
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
