name: Security and Dependency Management Workflow

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM UTC
  workflow_dispatch:
  repository_dispatch:
    types: [security_alert]

permissions:
  actions: read
  checks: write
  contents: read
  deployments: write
  issues: write
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: write

jobs:
  security-dependency-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Context
        id: setup-context
        uses: ./.github/actions/setup-context-and-prerequisites
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Security Checks
        id: security-checks
        uses: ./.github/actions/run-security-checks
        with:
          working-directory: ${{ steps.setup-context.outputs.repository_root_directory }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: AI Analysis of Security Report
        id: ai-analysis
        uses: ./.github/actions/ai-generate-content
        with:
          content-type: "security_analysis"
          context-data: |
            {
              "vulnerability-report": ${{ steps.security-checks.outputs.vulnerability-report }}
            }
          template-path: .github/templates/security_vulnerability_report_template.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Dependencies
        id: update-dependencies
        uses: ./.github/actions/update-dependencies
        with:
          repository-context: ${{ steps.setup-context.outputs.repository-context }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: AI Generate Update Summary
        id: ai-update-summary
        uses: ./.github/actions/ai-generate-content
        with:
          content-type: "dependency_update_summary"
          context-data: |
            {
              "updates-list": ${{ steps.update-dependencies.outputs.updates-list }}
            }
          template-path: .github/templates/dependency_update_pr_description.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for Updates
        id: create-pr
        uses: ./.github/actions/create-or-update-pr
        with:
          branch-name: ${{ steps.setup-context.outputs.feature_branch_prefix }}security-dependency-update
          pr-title: "Security and Dependency Updates"
          pr-body: ${{ steps.ai-update-summary.outputs.generated-content }}
          base-branch: ${{ steps.setup-context.outputs.main_branch }}
          labels: ${{ steps.setup-context.outputs.security_update_labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Security Policy
        id: update-security-policy
        uses: ./.github/actions/update-security-policy
        with:
          security-report: ${{ steps.security-checks.outputs.vulnerability-report }}
          ai-analysis: ${{ steps.ai-analysis.outputs.generated-content }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Critical Security Issue
        id: create-critical-issue
        if: ${{ steps.security-checks.outputs.critical_vulnerabilities > 0 }}
        uses: ./.github/actions/create-issue
        with:
          issue-type: "security_vulnerability"
          issue-details: ${{ steps.security-checks.outputs.vulnerability-report }}
          issue-template: .github/templates/critical_security_issue_template.md
          issue-title: "Critical Security Vulnerabilities Detected"
          labels: ${{ steps.setup-context.outputs.security_critical_labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Notification
        id: send-notification
        uses: ./.github/actions/send-notification
        with:
          notification-type: "security_update"
          notification-data: |
            {
              "vulnerability-report": ${{ steps.security-checks.outputs.vulnerability-report }},
              "ai-analysis": ${{ steps.ai-analysis.outputs.generated-content }},
              "pr-url": ${{ steps.create-pr.outputs.pr-url }},
              "critical-issues": ${{ steps.security-checks.outputs.critical_vulnerabilities }}
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
