name: Update Develop to Main PR

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch All Branches
        run: git fetch --all

      - name: Generate PR Content
        id: pr_content
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          set -e
          echo "Generating PR content for develop to main"
          commits=$(git log --format=%B origin/main..origin/develop)
          
          pr_data=$(curl -X POST https://api.groq.com/openai/v1/chat/completions \
            -H "Authorization: Bearer $GROQ_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "llama-3.1-70b-versatile",
              "messages": [
                {"role": "system", "content": "You are an AI assistant tasked with creating pull request titles and descriptions. Respond in JSON format with keys 'title' and 'body'."},
                {"role": "user", "content": "Create a pull request title and description for merging develop into main with the following commits: '$commits'"}
              ],
              "temperature": 0.7,
              "response_format": {"type": "json_object"}
            }')
          
          echo "PR_TITLE=$(echo $pr_data | jq -r '.choices[0].message.content.title')" >> $GITHUB_ENV
          echo "PR_BODY=$(echo $pr_data | jq -r '.choices[0].message.content.body')" >> $GITHUB_ENV

      - name: Create or Update Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          echo "Processing PR from develop to main"
          
          existing_pr=$(gh pr list --head develop --base main --json number --jq '.[0].number')
          
          if [ -z "$existing_pr" ]; then
            echo "Creating new PR from develop to main"
            gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head develop || {
              echo "Failed to create PR. This might be due to no new commits or other issues."
              exit 0
            }
          else
            echo "Updating existing PR #$existing_pr from develop to main"
            gh pr edit "$existing_pr" --title "$PR_TITLE" --body "$PR_BODY"
          fi

          issues=$(gh issue list --search "develop" --json number,title)
          if [ -n "$issues" ]; then
            echo "Linking related issues to PR"
            echo "$issues" | jq -r '.[] | "- #\(.number) \(.title)"' >> $PR_BODY
            gh pr edit --body "$PR_BODY"
            
            echo "$issues" | jq -r '.[]' | while read -r issue; do
              number=$(echo $issue | jq -r '.number')
              gh issue comment $number --body "This issue is addressed in PR #$(gh pr view --json number -q .number)"
            done
          fi